### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by 0mp** [svenstaro/miniserve#1]
I am rather new to the Cargo build system but shouldn't there be a Cargo.lock file?

I guess it is not needed as it could be generated from Cargo.toml but it makes porting things much easier.

Cheers!

**Comment by svenstaro** [comment]
True. The rule is: Applications should check it into git, libraries should not.

**Comment by 0mp** [comment]
Alright 👍 Thanks for the explanation.
