### ISSUE TITLE
Serve cwd by default?

### ISSUE THREAD

**Issue by colindean** [svenstaro/miniserve#10]
It'd be great if running `miniserve` without any arguments served the current working directory.

I'd be happy to make this change, by giving the PATH argument a default of `.`, if this is amenable.

**Comment by svenstaro** [comment]
I'm not sure. It could be a potential security problem if someone is just mistyping `miniserve` and wanted to see its options. I think I like the explicit `miniserve .` but I can be convinced otherwise.

**Comment by colindean** [comment]
I think it's a fair concern that a user may inadvertently launch it. Maybe when launched without an explicit path, it defaults to `.` but sleeps for a second or two after printing something like this:

```
Invoke with -h|--help to see options. Serving the current directory in 3… 2… 1…
miniserve is serving your files at http://localhost:8080
Currently serving path /Users/colin/Documents/Finance/Personal/2017/stock
Quit by pressing CTRL-C
```

This gives the user just enough time to send SIGTERM if they did it accidentally and waiting a second or two for the server to come up is completely rational anyway.

**Comment by colindean** [comment]
Better yet, what about a format like this?

```
Serving current directory:  /Users/colin/mysecrets
Invoke with -h|--help to see options or invoke with `miniserve .` to hide this advice. 
Starting server in 3… 2… 1…
miniserve is serving /Users/colin/mysecrets at http://localhost:8080
Quit by pressing CTRL-C
```

**Comment by svenstaro** [comment]
I added this. Can you check it out?

**Comment by colindean** [comment]
What great timing. I was just documenting using `python -m SimpleHTTPServer 9999` or the new Python 3 syntax in something and distinguishing that was getting annoying!

I see only after doing `cargo install --force miniserve` that it's not been released yet.

```
$ make build-apple
$ target/x86_64-apple-darwin/release/miniserve --port 9999
miniserve v0.1.5
Info: miniserve has been invoked without an explicit path so it will serve the current directory.
      Invoke with -h|--help to see options or invoke as `miniserve .` to hide this advice.
Starting server in 3… 2… 1…
Serving path /Users/colin/Source/Personal/miniserve at http://localhost:9999
Quit by pressing CTRL-C
```

Very nice. Thanks!

**Comment by svenstaro** [comment]
Yeah, will release soon. :)
