### ISSUE TITLE
Error: Refusing to start as no explicit serve path set..

### ISSUE THREAD

**Issue by Timmer2021** [svenstaro/miniserve#1027]
Trying to install miniserve via docker, using a stack in Portainer.. 

Here is the stack: 
version: '3.3'
services:
    miniserve:
        container_name: miniserve
        volumes:
            - '/volume1/docker/miniserv:/tmp'
        ports:
            - '28529:8080'
        restart: unless-stopped
        image: 'docker.io/svenstaro/miniserve:latest'

The container starts successfully but the following is what's displayed.. 

17:32:51 [ERROR] Refusing to start as no explicit serve path was set and no interactive terminal was attached
17:32:51 [ERROR] Please set an explicit serve path like: `miniserve /my/path`
Error: Refusing to start as no explicit serve path was set and no interactive terminal was attached
Please set an explicit serve path like: `miniserve /my/path`

Any ideas?

Tks.
Tim.

**Comment by shemarmc** [comment]
Though I am not using this stack you could try to append the following to your miniserve service
```yaml
    command: >-
      /tmp
```
This should serve the path you have mounted

**Comment by svenstaro** [comment]
If no interactive terminal is attached and not explicit path is given, `miniserve` will refuse to start for security reasons. I think the tip by @shemarmc should help in your case as that provides an explicit path. Please request to reopen if that doesn't help.
