### ISSUE TITLE
Cannot serve on ramdisk

### ISSUE THREAD

**Issue by Izumiko** [svenstaro/miniserve#1054]
I created a ramdisk with ImDisk, labeled as `Z:`. Then I encountered the following problems:
```cmd
Z:\>miniserve .
13:48:32 [ERROR] Failed to resolve path to be served
13:48:32 [ERROR] caused by: 函数不正确。 (os error 1)
Error: Failed to resolve path to be served
caused by: 函数不正确。 (os error 1)
```

Any subpath of the ramdisk cannot be served.

**Comment by svenstaro** [comment]
Hm no idea about this. Is there anything special about ramdisks on Windows?

**Comment by Izumiko** [comment]
No idea either. Maybe the simulated disk lacks some features? I'll avoid starting miniserve on ramdisk.

**Comment by misaka4a92** [comment]
@Izumiko This seems related to https://github.com/rust-lang/rust/issues/48249, might need to be fixed by upstream
