### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by impishian** [svenstaro/miniserve#1075]
macOS 13.1

$ ./miniserve-0.23.0-x86_64-apple-darwin --version
Segmentation fault: 11

on macOS, I have to build it myself.

**Comment by sujitawake** [comment]
FYI - I am facing the same issue as well on my Mac Ventura.

**Comment by svenstaro** [comment]
Are you also using x86_64? Can you try aarch64?

**Comment by sujitawake** [comment]
As suggested, tried the `aarch64` release binary too. It says `bad CPU type in executable: miniserve` which is kind of obvious.

Pretty much clueless what might be going wrong here. Each time I download and run the compiled binary for `x86_64` arch, it keeps crashing and throws up `Segmentation fault`
