### ISSUE TITLE
stream error: Request parse error: Invalid Header provided

### ISSUE THREAD

**Issue by xxxleonxx** [svenstaro/miniserve#1078]
get error ：  stream error: Request parse error: Invalid Header provided

**Comment by svenstaro** [comment]
You need to add more information. There's nothing here.

**Comment by Alluseri** [comment]
<img src="https://cdn.nest.rip/uploads/13f21e3d-4cec-4097-88cc-ccd4c7d0b87d.png">

**Comment by svenstaro** [comment]
What's the request you sent?
