### ISSUE TITLE
Drop or replace get_if_addrs due to future incompatibilities with rust due to winapi dep.

### ISSUE THREAD

**Issue by CryoRenegade** [svenstaro/miniserve#1079]
I will be the first to say that I dont know that much about programming in rust or how it works internally, but as an avid user of cli utils that are written in rust, with miniserve being a significant part of my operations (Seriously, u guys rock).
Earlier this month, i compiled miniserve on a windows server and got the warning that winapi would cause this project to stop compiling due to a old version on winapi. After a quick cargo tree, i found that get_if_addrs was the culprit and that it has been archived on [github](https://github.com/maidsafe-archive/get_if_addrs) and is no longer being worked on.
With this, eventually miniserve will not work on windows (or at least x86_64-windows-msvc).
Heres a paste bin of the future-incompatibilities report (https://pastebin.com/4Bhuhjdt)

**Comment by mpipalia** [comment]
Looks like this functionality was moved into the if-addrs crate: https://crates.io/crates/if-addrs

**Comment by svenstaro** [comment]
I switched to `if-addrs` and all is well!
