### ISSUE TITLE
curl footer?

### ISSUE THREAD

**Issue by jgranduel** [svenstaro/miniserve#1103]
Hi, 

thanks **A LOT** for this project. 

I've seen that the `wget footer` issue (see #1043) is now solved in 0.23 version. Very useful for large folder. Thanks again.
Would it be possible to have a `curl` equivalent footer?  I am asking that because on Windows, curl is now present in `C:\Windows\System32\` on Windows-10+ AFAIK, but wget has to be installed. Hence it might be easier to use it by default. Do you think it would be feasable?

**Comment by svenstaro** [comment]
As far as I'm aware, curl is unable to fetch directories recursively. Am I missing something here?

**Comment by jgranduel** [comment]
You were and are right! [https://daniel.haxx.se/docs/curl-vs-wget.html](https://daniel.haxx.se/docs/curl-vs-wget.html).
My mistake stems from the confusion with curl option `--create-dirs` , but indeed, I first need to get all file paths or urls. Forget my request! Thx

**Comment by svenstaro** [comment]
No worries!
