### ISSUE TITLE
Add "-Ctarget-feature=+crt-static" to rust flags for msvc compile to get rid off the dependency on "vcruntime140.dll"

### ISSUE THREAD

**Issue by elmkni** [svenstaro/miniserve#1105]
Hi there!

My name is Elmar Knittel and I use [Miniserve](https://github.com/svenstaro/miniserve) in conjunction with [x-ite](https://create3000.github.io/x_ite).

[Miniserve](https://github.com/svenstaro/miniserve) is a fantastic tool for programs like [x-ite](https://create3000.github.io/x_ite) that use `XMLHttpRequest` to pull in files (images etc) and **therefore need a localhost server** because of restricted [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (cross origin resource sharing) policy!

Here's my request:

Please consider adding `-Ctarget-feature=+crt-static` to [Rust](https://www.rust-lang.org) flags **for msvc compile** to get rid off the dependency on `vcruntime140.dll`.

`vcruntime140.dll` **is not part of standard** [Windows](https://www.microsoft.com/en-us/software-download/windows10) (not even for [Windows11](https://www.microsoft.com/en-us/software-download/windows11))!

At the moment I undergo the inconvenience to download the newest [Rust](https://www.rust-lang.org)-compiler, set it up and recompile [Miniserve](https://github.com/svenstaro/miniserve) with `-Ctarget-feature=+crt-static` from source (including the download of over 300 [Rust](https://www.rust-lang.org)-crates) for every new version of [Miniserve](https://github.com/svenstaro/miniserve).

**The increase in size is only 33792 bytes** if packed with [upx](https://upx.github.io/) `-9 --ultra-brute` (96256 bytes unpacked)!

Best regards,

Elmar

**Comment by svenstaro** [comment]
That's odd. I regularly use miniserve on fairly fresh Windows installs and this has not been an issue so far. I will definitely consider adding that flag though but I'd first like to try to recreate the issue, if possible.

**Comment by svenstaro** [comment]
I made a PR which should address this. You should be able to download the resulting binaries from the PR directly.

**Comment by elmkni** [comment]
What's PR? Where can I download the statically linked binary?

**Comment by svenstaro** [comment]
If you scroll all the way to the bottom here: https://github.com/svenstaro/miniserve/actions/runs/4759134616?pr=1107

**Comment by elmkni** [comment]
Got it!

Thanks a lot for your efforts, saves me a lot of work in the future!

Best regards,

Elmar

**Comment by svenstaro** [comment]
Just to confirm: it works for you as expected?

**Comment by elmkni** [comment]
Yes, it does!
