### ISSUE TITLE
Musl build for amd64 still requires glibc 2.34

### ISSUE THREAD

**Issue by degaart** [svenstaro/miniserve#1143]
Filename: miniserve-0.23.2-x86_64-unknown-linux-musl

`file` says it's a static executable, yet it requires glibc 2.34 at runtime (which defeats the purpose of a musl build).

**Comment by martadinata666** [comment]
pretty curious, how do you replicate this? I tried the musl and I can't get libc error.

**Comment by degaart** [comment]
Run it on an old distro where glibc version < 2.34, like CentOS 7, Ubuntu 20.04 LTS, or debian 11. It will spew out an error about GLIBC_2.34 symbol not found.
