### ISSUE TITLE
question: run miniserver on OpenWrt 22.03.5 in NanoPi R4S router

### ISSUE THREAD

**Issue by asmwarrior** [svenstaro/miniserve#1155]
Hi, I have a [NanoPi R4S - FriendlyELEC WiKi](https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R4S) which I installed the OpenWrt on this hardware board.

I see the CPU is: `CPU: big.LITTLE，Dual-Core Cortex-A72(up to 2.0GHz) + Quad-Core Cortex-A53(up to 1.5GHz)`

My question is: is it possible to run miniserver on this system?

I see there are a lot of release files, which one should I download?

Thanks.

**EDIT:** This is the result of the command `uname -a`

`Linux FriendlyWrt 5.15.78 #1 SMP PREEMPT Wed May 24 12:56:51 CST 2023 aarch64 GNU/Linux`

**Comment by asmwarrior** [comment]
So, do I need to use this one:

[miniserve-0.23.2-aarch64-unknown-linux-gnu](https://github.com/svenstaro/miniserve/releases/download/v0.23.2/miniserve-0.23.2-aarch64-unknown-linux-gnu) ?

Thanks.

**Comment by asmwarrior** [comment]
I just tried it on my OpenWrt shell, and I think I can't run the above mentioned executable, even I added the verbose option:

~~~~
root@FriendlyWrt:/tmp/miniserve# ./miniserve-0.23.2-aarch64-unknown-linux-gnu -p 50018 --verbose ./
~~~~

Nothing happened when I run the above command.

**Comment by asmwarrior** [comment]
OK, I think I have found the issue, the OpenWrt I use is using the `musl` library, so I have to download the file: [miniserve-0.23.2-aarch64-unknown-linux-musl](https://github.com/svenstaro/miniserve/releases/download/v0.23.2/miniserve-0.23.2-aarch64-unknown-linux-musl)

Then I can run the previous mentioned command correctly, and I see the server runs on my OpenWrt now! Great!

**Comment by svenstaro** [comment]
Happy to hear!

**Comment by asmwarrior** [comment]
Forgot to say the miniserve is a great tool! Thanks for the sharing!
