### ISSUE TITLE
permission denied: unknown

### ISSUE THREAD

**Issue by HzaZoro** [svenstaro/miniserve#1180]
os: truenas scale 
mini-server.version: v0.24.0
deploy type: docker

![image](https://github.com/svenstaro/miniserve/assets/46878089/055b21cc-0274-4db2-9053-00e1cacdc7cc)

thanks,please help me to fix it

**Comment by svenstaro** [comment]
This doesn't seem to have anything to do with miniserve. As you can see, it's exciting before that.

**Comment by HzaZoro** [comment]
> This doesn't seem to have anything to do with miniserve. As you can see, it's exciting before that.

yes,i use env $PATH and success
