### ISSUE TITLE
.tar.gz download is broken and only downloads uncompressed tar

### ISSUE THREAD

**Issue by SuperTux88** [svenstaro/miniserve#1187]
When using `--enable-tar-gz` and clicking the "Download .tar.gz" it still only downloads a uncompressed tar file. It has a `.tar.gz` file extension, but trying to open the `.tar.gz` fails, because it's actually not compressed, so uncompression fails (renaming to `.tar` or opening it otherwise without trying to uncompress it works). The checksum of the downloaded file is exactly the same as when using `--enable-tar` and clicking the "Download .tar" button, so it is indeed just a normal `.tar`.

Version: 0.24.0
OS: Gentoo Linux
Browser: Tested in Firefox and Chromium, so it doesn't look like it's a browser-issue

**Comment by svenstaro** [comment]
Please check master!
