### ISSUE TITLE
Miniserve cutting ends of files off.

### ISSUE THREAD

**Issue by Qwertie-** [svenstaro/miniserve#12]
Most of the times I use miniserve it will cut the ends of files off. No idea what causes it but it happens regularly.

Miniserve version: 0.1.5
OS: Fedora 28

**Comment by svenstaro** [comment]
I can't reproduce. Do you have a sample file for me? Does it happen after a certain time elapsed or a file size?

**Comment by svenstaro** [comment]
Still can't reproduce and I don't have a test case. Please reopen if this problem exists.
