### ISSUE TITLE
The error/warning logs that appear in integration test is pretty annoying

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#120]
The test logs does not show them before due to `miniserve`'s logs being disabled by default. But now they are shown alongside normal test logs makes it hard to read the logs that actually matters.

![Screenshot of my terminal](https://user-images.githubusercontent.com/11488886/57965891-b9177400-7974-11e9-8492-7fc854f7c9e5.png)

## Suggestion

Do not redirect `stderr` output of subprocess to parent's `stderr`.

---

**P.S.** I am not familiar with `std::process` so I am going to waiting for someone else to do it.

**Comment by svenstaro** [comment]
I didn't notice this before but I entirely agree. This is annoying to read.
