### ISSUE TITLE
This is a great app and just what I was looking for . . but the Podman install is _very_ slow for uploading phone JPGs

### ISSUE THREAD

**Issue by philiprhoades** [svenstaro/miniserve#1211]
Sven,

I love this app but is it slow because of using it via Podman - 58 JPGs uploading is taking forever . . 

Thanks!

Phil.

**Comment by svenstaro** [comment]
Hey Phil,

I think miniserve isn't the limiting factor here. I was able to push around 10 GBit in a benchmark so perhaps you're just hitting the limits of your connection?

I admit the upload feedback could be improved.

**Comment by philiprhoades** [comment]
Wow! - thanks for the lightning response!

Well I am using it via a Zero Tier connection but it is on the same LAN (ATM) so it should be fine . . I will try it via the normal LAN IP and see if that makes a difference - oh now that I think about it - I think ZT will be slower . . let me check . .

**Comment by philiprhoades** [comment]
Ah yes - it is ZT that is slow . . sorry - I should have thought of that . . 

Thanks again for a brilliant little app - I will have to look at the src to see how it works!

P.

**Comment by svenstaro** [comment]
Happy to hear and thanks for the kind words :)

**Comment by philiprhoades** [comment]
It just occurred to me that trying to understand how miniserve works might be a good way to start learning Rust? - what do you think? - overkill?

Would you have time to add summary / overview text to the different modules that would help newbies who want to contribute to get past the "Hello World!" stage?  When I looked at the source code I was a bit surprised about how much there was of it for such a little program . .

**Comment by svenstaro** [comment]
I would recommend learning Rust by writing smaller programs of your own first so you can better familiarize yourself with the syntax. Then you could write your own little web server using async. At that point you'll be much more familiar with Rust. 

Miniserve source code is already somewhat documented if you scroll through it. There could probably be more of it but I don't have time to add any but I'd be happy to accept contributions.

**Comment by philiprhoades** [comment]
Just did another test with my brother (we have trouble finding mutually convenient times) and we found a different problem:

Selecting more than two or three files resulted in a 403 error with: "Duplicate file found and override not setup" or words to that effect on his iPhone . . but I can't reproduce the problem on my Android phone . .
