### ISSUE TITLE
helmchart for the container and kubernetes

### ISSUE THREAD

**Issue by wrenix** [svenstaro/miniserve#1215]
Do you plan or interested to "maintain" an helmchart for your miniserve container image?

here i write one: https://codeberg.org/wrenix/helm-charts/src/branch/main/miniserve which i could publish here (with github-ci for releasing into an helm repo under the gh-pages and release-tags)

**Comment by svenstaro** [comment]
I'm not sure. The helm chart you have there is almost 600 lines of YAML whereas miniserve is almost 6000 lines of Rust. I don't really feel like adding 10% LOC  for a deployment system and Kubernetes doesn't really reflect the general philosophy of miniserve anyway and it's probably not a particularly popular pairing. I think the [systemd service file](https://github.com/svenstaro/miniserve/blob/master/packaging/miniserve%40.service) is much more digestible.

How about this: You could add a PR to advertise your community-maintained helm chart?

**Comment by wrenix** [comment]
Oh thanks, i forgot to create a PR.
