### ISSUE TITLE
Hide "Create Directory" panel for folders without write-permission

### ISSUE THREAD

**Issue by Switch123456789** [svenstaro/miniserve#1249]
Imo it would make sense to hide it in the same way as the upload-panel, since it is non-functional anyway.

**Comment by svenstaro** [comment]
Maybe grey it out with an on-hover alt text? Would you like to submit a PR for that?

**Comment by Switch123456789** [comment]
Sorry I am late :see_no_evil: I would do it but I am very inexperienced, it would take me forever. But since the file-upload-panel already behaves in the exact same way I wish the create-directory-panel to work like, my guess is that copy-pasting the code for this behavior should be 99% of the work?

**Comment by Atreyagaurav** [comment]
So it looks like it is just a single line change, simple enough to not show the creation folder at all.

If you want it greyed out, then we should probably do it for both of them. Like show them greyed out when there are some directories with upload allowed but not the current one, remove it completely if there are none with upload allowed.
