### ISSUE TITLE
Automate binary deployment for AUR

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#125]
## Problem

The [miniserve AUR](https://aur.archlinux.org/packages/miniserve/) right now compiles to code, which takes time.

I also have [my own AUR](https://aur.archlinux.org/packages/miniserve-bin/) but it's inconvenient for me to update it on every release.

## Suggestion

Integrate the process of AUR deployment into Travis CI.

**Comment by svenstaro** [comment]
Closing as this is now in Arch Linux [community](https://archlinux.org/packages/community/x86_64/miniserve/).
