### ISSUE TITLE
Compile issue when installing via `cargo` method

### ISSUE THREAD

**Issue by t-391** [svenstaro/miniserve#1271]
Hello, I attempted to install miniserve using `cargo` with the following command:

`cargo install --locked miniserve`

On my Ubuntu server. However, I got a few errors during the build/compile. Here is a snippet. It is repeated in the areas of code where `is_terminal` gets used:

```
error[E0658]: use of unstable library feature 'is_terminal'
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.24.0/src/main.rs:1:21
  |
1 | use std::io::{self, IsTerminal, Write};
  |                     ^^^^^^^^^^
  |
  = note: see issue #98070 <https://github.com/rust-lang/rust/issues/98070> for more information
```
I can of course provide full logs is that would be beneficial. I made sure to get my rust installation fully updated before starting. Do you have any recommendations to troubleshoot?

The [related rust support thread](https://github.com/rust-lang/rust/issues/98070) seems to have a lot of activity.

**Comment by svenstaro** [comment]
Pretty sure you're using an old version of Rust. If you update this problem should get fixed.

**Comment by t-391** [comment]
> Pretty sure you're using an old version of Rust. If you update this problem should get fixed.

Of course you were right. Thank you for your advice. Solved!
