### ISSUE TITLE
Unable to serve files with embedded newline

### ISSUE THREAD

**Issue by Dialga** [svenstaro/miniserve#1294]
If a filename has an embedded newline, opening it in the browser will result in a "failed to parse header value" error.
Note: python http.server, php -S and darkhttpd are able to serve files with newlines successfully.

**Comment by svenstaro** [comment]
This is a problem in actix-files. I made an issue upstream.

**Comment by svenstaro** [comment]
I submitted a fix for this here: https://github.com/actix/actix-web/pull/3235

Hopefully it gets merged and released soon. :)
