### ISSUE TITLE
Does it support hiding some files?

### ISSUE THREAD

**Issue by Zruto** [svenstaro/miniserve#1307]

**Comment by svenstaro** [comment]
Is this the same as #1304?

**Comment by Zruto** [comment]
Yes, is this feature available now?

**Comment by svenstaro** [comment]
No, would you like to make a specification and maybe even try to take a stab at implementing this?

**Comment by Zruto** [comment]
Sorry, I'm not very good at it

**Comment by svenstaro** [comment]
Closing as a duplicate of #1304.

**Comment by svenstaro** [comment]
Oh, just remembered, you might be interested in miniserve's feature to hide .dotfiles by default.
