### ISSUE TITLE
Add cli flag to disable indexing

### ISSUE THREAD

**Issue by dyc3** [svenstaro/miniserve#1328]
Sometimes I use miniserve to serve some files over the public internet temporarily, usually for file sharing. And sometimes I forget to turn off the server when I'm done. It would be nice if I could disable indexing so that its a little bit harder to enumerate all the files I have in the folder that is being served.

I'd be willing to implement this myself. Just let me know of any gotchas I should look out for.

**Comment by svenstaro** [comment]
I'm willing to accept a contribution for this. Just make sure to add a test that shows what the proper behavior is. :)
