### ISSUE TITLE
Help me avoiding false clean build of AUR package

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#143]
I use a tool called `yay` to install this program from an aur package called `miniserve-bin` which download the binary from GitHub Release directly. Every time I update, `yay` asks if the packages need to be rebuilt (many packages, `miniserve-bin` is one of them), which I mistakenly typed `n` (for "no") causing miniserve not actually being updated.

## Suggestion

Attach version to the end of linux binary: <code>miniserve-linux-x86_64<strong>-0.5.0</strong></code> instead of just `miniserve-linux-x86_64`

## Alternate Suggestion

Hash every release artifacts from Travis CI into a text file and release it to GitHub.

**Comment by svenstaro** [comment]
Yeah sounds sensible but keep in mind that you can easily solve this downstream by setting an appropriate download name for the binary like this:

```
sources="miniserve-$pkgver"::url
```
