### ISSUE TITLE
OVERWRITE_FILES env var is not prefixed

### ISSUE THREAD

**Issue by lahwaacz** [svenstaro/miniserve#1457]
A small nitpick: the `OVERWRITE_FILES` environment variable is not prefixed with `MINISERVE_`:

https://github.com/svenstaro/miniserve/blob/873d485053f296b928f7bdd29a38e206a64222cb/src/args.rs#L198

Easy to fix, but I have no idea about the migration options...

**Comment by svenstaro** [comment]
Thanks for reporting this! The migration path is fairly easy pre-v1.0 :P
