### ISSUE TITLE
Suggestion: Serving index.html, index.xml, index.xhtml, index.htm

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#156]
## Why?

I want to serve some static website but I don't want to manually find `index.html` in a list of dozen items.

## Suggestion 1

Introduce a `--homepage index.html` option which instructs miniserve to serve `index.html` when the file is found within the folder.

## Suggestion 2

If `index.*` file is found within a folder, display a button next to "Download .tar.gz" that links to said file.

**Comment by svenstaro** [comment]
I quite like suggestion 1. Should be easy to implement, too.

**Comment by zicklag** [comment]
What do you think about adding a `-I` arg that would be a shortcut for `--index index.html`. I almost always want to have the default index, so having a short arg specifically for it would be nice.
