### ISSUE TITLE
Remove thread::sleep

### ISSUE THREAD

**Issue by wyhaya** [svenstaro/miniserve#159]
```rust
for c in "3… 2… 1… \n".chars() {
    print!("{}", c);
    io::stdout()
        .flush()
        .map_err(|e| ContextualError::IOError("Failed to write data".to_string(), e))?;
    thread::sleep(Duration::from_millis(500));
}
```
Should  delete `thread::sleep` to make the program open as soon as possible?

**Comment by svenstaro** [comment]
You can skip it if you provide an explicit path that you want to host. The general idea is that you can't shoot yourself in the foot by just typing miniserve somewhere and suddenly host a directory that you didn't want to. If you just want to host the current dir instantly, you can type 
```
miniserve .
```
