### ISSUE TITLE
Firefox is confused when downloading .gz

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#160]
Firefox corrupts files when downloading gzipped files. Probably a MIME type problem. Investigate.

**Comment by efx** [comment]
When I tried to download the `tar` or `tar.gz` of a directory, I noticed the following error printed to stdout of miniserve@0.5.0:
```
17:56:19 [ERROR] Error during archive creation: ArchiveCreationError("tarball", IOError("Failed to append the content of my-folder to the TAR archive", Os { code: 2, kind: NotFound, message: "No such file or directory" }))
```

**Comment by bjeanes** [comment]
I recently stood up a miniserve on my NAS for my friends and forgot about it. It got posted on an opendirectories subreddit and it got hammered for days. For one, miniserve did REALLY well and transferred 2TB of data in 2 days to hundreds of concurrent people (it would have been more but my home connection is only 100mbit up). 

However, I saw a LOT of errors like the one @efx posted. Not sure if it was the high concurrency, name or structure of specific files/directories, a mimetype error from certain browsers, or just an outright bug. But worth noting that the prevelance of that error was very high.

**Comment by svenstaro** [comment]
I've investigated this. The problem appears to be that `mime_guess` which uses `mime` sees the `gz` extension and returns `application/x-gzip` instead of the standard `application/gzip` which appears to confuse Firefox somehow. It still works properly if the file is actually saved somewhere. It just doesn't work if the file is directly opened. Perhaps I can just patch the mime crate for the time being. There doesn't appear to be any other effective workaround.

**Comment by svenstaro** [comment]
Ok, actually the problem was only in `mime_guess`. [I made a PR to fix the problem upstream](https://github.com/abonander/mime_guess/pull/66). In the meantime I guess we'll just patch our dependencies.
