### ISSUE TITLE
Trailing '/'

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#161]
## Why?

When https://github.com/svenstaro/miniserve/issues/156 is implemented, a problem arises:

Let's say we have directory `localhost:5000/foo` and file `localhost:5000/foo/index.html` which contains links and references to external resources. Accessing `localhost:5000/foo` would give content of `localhost:5000/foo/index.html`, hyperlinks within page of `localhost:5000/foo` would lead to wrong location (for example: `<img src='image.png'>` would refer to `localhost:5000/image.png` instead of `localhost:5000/foo/image.png`).

## Suggestions

Automatically correct the link by redirection:
  * Add trailing comma to directory path: Route `/foo` should redirect you to `/foo/`.
  * Remove trailing comma from directory path: Route `/foo/index.html/` should redirect you to `/foo/index.html`.

All links within a directory view (list of files and directories when serving a directory) should have trailing commas when appropriate:
  * Links to directory should have trailing comma.
  * Links to file should not have trailing comma.

**Comment by svenstaro** [comment]
Fixed by #158.
