### ISSUE TITLE
interest in a `--fallback-index` feature?

### ISSUE THREAD

**Issue by efx** [svenstaro/miniserve#192]
While working on #156 I realized I need a slightly related feature to support serving a single page JavaScript application that has routes (ember.js, react-router, others). Without this flag I would need to symlink everything which is a pain.

## example implementations
1. [devd's --notfound](https://github.com/cortesi/devd#serving-default-content-for-files-not-found)
2. Apache httpd's [`FallbackResource`](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#fallbackresource)

Would you be ok adding this feature to the project?

**Comment by efx** [comment]
While nice, I don't require this feature anymore. It also seems that I could accomplish this quite easily using [`actix-web`](https://actix.rs/docs/getting-started/) directly.

**Comment by svenstaro** [comment]
For the record: What in actix-web does this for you?

**Comment by efx** [comment]
@svenstaro Good question. I was thinking of following the tutorial to create my own server that would serve static files. Reading through miniserve's codebase and the actix getting started guide made me think I could do something like the example in https://actix.rs/docs/static-files/. This is entirely conjecture as I'm learning Rust and read through `miniserve` quickly.  😄 
I also prefer to keep projects focused and so wouldn't want to just add some thing that I felt like one day and the next decided against due to changing project requirements.
