### ISSUE TITLE
Some files cant get downloaded due to filename

### ISSUE THREAD

**Issue by Jikstra** [svenstaro/miniserve#229]
I currently have some files which I can't download (miniserve responds with a 404)
Filenames are:
```
OBSOLESZNZ - TestSession #01.cue
OBSOLESZNZ - TestSession #01.mp3
OBSOLESZNZ - TestSession #01.mp3
```

Probably because of the whitespaces and `#`

**Comment by DamianX** [comment]
Works on my machine. What OS are you running miniserve on?

**Comment by RandomOS** [comment]
miniserve version: 0.13.0 Linux amd64

I currently have some files which I can't download (miniserve responds with a 404)
Filenames are:
```text
bind9-host_1%3a9.10.3.dfsg.P4-8ubuntu1.18_amd64.deb
```

Result:
```text
404 Not Found

Route /16.04/bind9-host_1%3a9.10.3.dfsg.P4-8ubuntu1.18_amd64.deb could not be found
```
