### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by garoto** [svenstaro/miniserve#274]
Any chance of compiling a changelog from commit messages or similar?

**Comment by svenstaro** [comment]
I think just a dump of commit messages is less informative than the current changelog that I have for this project. I try to add all user facing changes to the current changelog. Do you think it is insufficient in its current form?

**Comment by garoto** [comment]
Oh, just found out that there's a `CHANGELOG.md` in the root of the repository. Is that file linked anywhere else?

My comment was targeted at the lack of release notes in github's `releases` sub-page.

**Comment by svenstaro** [comment]
I see. I can try to sync the release notes for GitHub releases with those in the changelog. Perhaps I can automate that somehow.

**Comment by garoto** [comment]
Perhaps adding a link to the `CHANGELOG.md` to the `README.md` might be good enough for people looking for it.
