### ISSUE TITLE
[Feature Request] Add upload feature

### ISSUE THREAD

**Issue by yangshuairocks** [svenstaro/miniserve#276]
It would be more useful if miniserve has upload feature. Please consider adding it.

**Comment by KSXGitHub** [comment]
Is this not enough?

![Screenshot](https://user-images.githubusercontent.com/11488886/77522115-46412880-6eb6-11ea-904b-9205b2a69811.png)

**Comment by yangshuairocks** [comment]
Oh, sorry I missed it. Thanks!
