### ISSUE TITLE
Official REST API - CRUD file server

### ISSUE THREAD

**Issue by KlockiLego** [svenstaro/miniserve#279]
It would be great if the server had a simple API to manage shared files.

This would allow easy server operation from a custom frontend.

Somothing like this:
https://github.com/Fluidbyte/Node-FSAPI
https://www.npmjs.com/package/crud-file-server
https://www.npmjs.com/package/express-rest-file-server

**Comment by Jikstra** [comment]
There is a specification to all this, it's not restapi/crud but it allows all the things one wants. It's called WebDAV.

**Comment by svenstaro** [comment]
Closing in favor of #293.
