### ISSUE TITLE
Allow different sort modes for file listing

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#28]
It would be nice to be able to sort the files differently. Currently, the ordering feels kind of wrong as the dirs are usually followed by the files but currently everything is only ordered alphabetically. It would be nice to get different order types. Maybe these order modes:

**dirsfiles**
```
dir1/
dir2/
dir3/
file1
file2
file3
```

**alpha**
```
A/
a
B
b/
C
c
```

**natural**
```
A/
B
C
a
b
c
```

**Comment by boastful-squirrel** [comment]
I'll be on it. Should we keep alphabetical order as default ?

**Comment by svenstaro** [comment]
I think it makes the most sense to order it like other web server listings
do: folders first and first, both sorted in alpha.

**Comment by boastful-squirrel** [comment]
Got it

**Comment by boastful-squirrel** [comment]
What should I do for the CLI ? Different options conflicting with eachothers, or a `sort` option that can take 3 values ? 

I mean, something like this:


```
miniserve --sort-foobar /tmp
```

or 
```
miniserve --sort=foobar /tmp
```

**Comment by boastful-squirrel** [comment]
So I implemented dirsfiles and alpha, what's "natural" exactly ? In your example, it looks like dirsfiles :P

**Comment by svenstaro** [comment]
Yeah I suppose that's a bit misleading what I wrote there. So the general
idea was to have either ASCII value based ordering or alphabetical ordering
whereby you would get ABCabc (ASCII) as opposed to AaBbCc (alpha).

Natural sorting actually just changes how you treat numbers:
https://en.m.wikipedia.org/wiki/Natural_sort_order
