### ISSUE TITLE
miniserve formula downgraded to v0.3.0

### ISSUE THREAD

**Issue by chenrui333** [svenstaro/miniserve#291]
Due to the compilation issue with depending on nightly Rust, the formula has been downgraded to v0.3.0 (https://github.com/Homebrew/homebrew-core/pull/53095).

Posting in here for visibility. Thanks!

**Comment by svenstaro** [comment]
Thanks. I'll make it compile on stable going forth.

**Comment by chenrui333** [comment]
@svenstaro any update on the `stable` dependency efforts (just saw the latest 0.7.0 failed to build on Rust stable too). Thanks!

**Comment by svenstaro** [comment]
Not quite yet, working on it!

**Comment by chenrui333** [comment]
Cool, thanks for the status report. :)

**Comment by chenrui333** [comment]
Checking this out on the v0.8.0 release, https://github.com/Homebrew/homebrew-core/pull/60733

**Comment by chenrui333** [comment]
looks like still no luck with 0.9.0 release?

**Comment by svenstaro** [comment]
Nah, I'm expecting one more contribution currently that concerns templating and then I'll do the change in one go without annoying contributors. :)

**Comment by svenstaro** [comment]
@chenrui333 miniserve now compiles on stable Rust!

**Comment by chenrui333** [comment]
@svenstaro works on my side, thanks a lot! Closing the issue.
