### ISSUE TITLE
how to upload file with curl?

### ISSUE THREAD

**Issue by yhnu** [svenstaro/miniserve#302]
how to upload file with curl? not via web

**Comment by mhuesch** [comment]
@yhnu try this:

```
curl -F 'path=@$PATH' http://localhost:9991/upload\?path\=/
```

where $PATH is replaced the path to the file.

**Comment by svenstaro** [comment]
It would be neat if someone could document this in the README.

**Comment by svenstaro** [comment]
I think this would be good to document. :) Let's leave it open until it is documented in the README.

**Comment by mhuesch** [comment]
@svenstaro I just made a PR: https://github.com/svenstaro/miniserve/pull/460 let me know how it looks 🙂
