### ISSUE TITLE
URLs are wrong in the UI

### ISSUE THREAD

**Issue by NightMachinary** [svenstaro/miniserve#312]
The URLs are `http://video/?sort=date&order=asc` for a link that should actually be `http://ipAddress:8080/video/`.

**Comment by NightMachinary** [comment]
This problem went away by itself, but it has now returned. Restarting miniserve didn’t solve the problem in both instances.

**Comment by Jikstra** [comment]
On what filesystem/os does this happen? What is the full path where miniserve is running/serving from?

**Comment by NightMachinary** [comment]
It’s Ubuntu 20, served from ~/Downloads . I switched to Caddy, so feel free to close the issue.
