### ISSUE TITLE
Break out HTML and use a templating engine

### ISSUE THREAD

**Issue by boastful-squirrel** [svenstaro/miniserve#34]
_Originally posted by @svenstaro in https://github.com/svenstaro/miniserve/pull/32_

Just creating the issue so we can remember it. I'll probably do it after #32 is merged and #33 is done

**Comment by boastful-squirrel** [comment]
I also think we should split HTML/CSS and js. CSS is a static file, JS should be static too, so I suggest we put them in a separate file? Then we just call them from the HTML.

**Comment by svenstaro** [comment]
Yes, I think you're right. It would be better to just break out the HTML and save it as normal HTML as opposed to using typed-html. That's not the right tool for this job at this point. Just separate out everything and use normal templating.

**Comment by boastful-squirrel** [comment]
Do you have any recommendation for the template engine crate we should use ? I know `aksama` but it might be too big ? `maud` seems very promising too, though it requires nightly, `horrorshow`, despite its name, seems cool too

**Comment by svenstaro** [comment]
I think `handlebars` does everything we need. I don't think we need logic inside of our templates.

**Comment by boastful-squirrel** [comment]
Right, I'll take a look at it.

**Comment by boastful-squirrel** [comment]
I'm starting this today.

**Comment by boastful-squirrel** [comment]
I'm having quite good results with Maud at the moment, it's blazingly fast ! I'll keep in touch
