### ISSUE TITLE
Make this work on stable/switch templating engine

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#347]
Sadly it doesn't really look like maud will become available on stable anytime soon and we should, therefore, look into switching the templating engine. Either askama or tera might be a good fit.

**Comment by lambda-fairy** [comment]
FYI, lambda-fairy/maud#17 is now closed :slightly_smiling_face:

**Comment by svenstaro** [comment]
Oh, that's amazing! I'll update right this instant.
