### ISSUE TITLE
Show last modified date in listing

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#36]
I actually had this requirement a few minutes ago that I wanted to see the modified date in the file listing.

**Comment by boastful-squirrel** [comment]
Should be pretty quick to do, since we already retrieve metadata of the file :) The only thing is: what format for the date should we use ?

**Comment by boastful-squirrel** [comment]
Also, I think we should add a sorting option based on modification date too, while we are at it.

**Comment by svenstaro** [comment]
Let's allow for setting a custom date formatting specifier. I'm sure
whatever Rust library we use to output the date can just directly eat a
format string and will also have some sane defaults such as ISO 8601 or RFC
3339 so we don't have to reinvent the wheel. Let's make it ISO by default
though since it's easy to read when it's sorted.

Also I like the idea of being able to sort by date, of course. :)

**Comment by boastful-squirrel** [comment]
What do you think about using a crate for “humanizing” the duration ? I mean, instead of showing a date, something like “4 days ago”, “3 minutes and 12 seconds ago” would be great, I think

**Comment by boastful-squirrel** [comment]
<img width="1339" alt="screenshot 2019-02-16 at 15 09 21" src="https://user-images.githubusercontent.com/47121073/52900925-debda180-31fc-11e9-9b47-9051d880a894.png">

Something like this :)
