### ISSUE TITLE
tar and zip not working

### ISSUE THREAD

**Issue by barberws** [svenstaro/miniserve#363]
Running on a beaglebone black system. Running into this issue when using the tar or zip option:

11:01:39 [ERROR] Error during archive creation: ArchiveCreationError("zip", ArchiveCreationError("Failed to create the ZIP archive", IOError("Could not get file metadata", Os { code: 2, kind: NotFound, message: "No such file or directory" })))

both tar and zip are installed and working on the system. Not sure where else to look. Are there any other dependencies that I need to ensure are installed?

Update: tar and tar.gz both seem to work now (some kind of temporary issue?), but zip is producing 0byte files.

**Comment by svenstaro** [comment]
Interesting. What's the underlying file system?

**Comment by barberws** [comment]
ext4

**Comment by barberws** [comment]
btw, gotta say I love this program. Thanks for writing it.

**Comment by barberws** [comment]
just found that the zip utility works too. I'm guessing that the size of the folders I was trying to zip were too big, which I'm guessing is a limitation due to the limited amount of RAM on the beaglebone. Would that be correct?

**Comment by svenstaro** [comment]
Yes, sadly zip can't be streamed. See `miniserve --help` which even informs the user about this possible problem. I believe this is a limitation of zip.

**Comment by svenstaro** [comment]
By the way, tar can stream just fine and so you shouldn't run into the same issues using that.

**Comment by barberws** [comment]
No worries,  it looks like now Windows 10 supports tar.gz natively and that's all I need. Thanks for your help!

**Comment by svenstaro** [comment]
Sweet, I'll consider this fixed then. :P

**Comment by pvonmoradi** [comment]
@svenstaro Is there a way to signal the error to the front-end? Currently the damaged zip file could successfully be downloaded.

**Comment by svenstaro** [comment]
@pvonmoradi would you like to try to tackle that issue?

**Comment by pvonmoradi** [comment]
> @pvonmoradi would you like to try to tackle that issue?

Unfortunately, I don't know Rust (yet), sorry.
