### ISSUE TITLE
Tiny typo "now ago"

### ISSUE THREAD

**Issue by KevCui** [svenstaro/miniserve#372]
There is a tiny typo "now ago" when creating new file and refresh server page immediately. In this case, it's better to show only "now" without "ago".

![1599904310](https://user-images.githubusercontent.com/14293537/92992967-ba1bcf80-f4ee-11ea-9c5e-76732826c9ad.jpg)

**Comment by svenstaro** [comment]
Oh good catch. Wanna make a PR?

**Comment by KevCui** [comment]
@svenstaro Sure thing, please review PR.
