### ISSUE TITLE
Request: Generate shell completion files

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#377]
This application uses [structopt](https://github.com/TeXitoi/structopt), which uses [clap](https://clap.rs/), which has APIs to generate completion code for bash, fish, zsh, powershell, and elvish. You can use [`structopt::clap::App::gen_completions`](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.gen_completions) or [`structopt::clap::App::gen_completions_to`](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.gen_completions_to) to generate completion code from your `StructOpt::clap()`.

## How to provide completion code

There are two common ways of providing completion code:

### Embedded functionality within the main application

Create a subcommand (`miniserve completions <shell>`) or option (`miniserve --completions=<shell>`) that prints completion code to stdout and exits.

**Pros:**
  * Simple to implement.
  * Simple for repo owner to distribute: It is already within the main application.
  * Completions will always be up-to-date.

**Cons:**
  * Completion is almost always generated once, after that, the sub-functionality is considered bloat.
  * More complicated for Linux distros to distribute: It must execute miniserve to generate completions.

### Generate completions ahead of time

Use [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to generate completions whenever the main application is built.

**Pros:**
  * Completion is generated ahead of time, separated from the main application, user just has to download what is needed, no unnecessary bloat.
  * Simple for Linux distros to distribute: Just install the pre-generated completions.

**Cons:**
  * More complicated to implement.
  * Repo owner must distribute completion files either via GitHub Release or via the git repo itself.
  * If repo owner chooses to distribute completion via git repo, they must make sure completions always up-to-date.

**Comment by svenstaro** [comment]
Yeah good idea. Being a distribution maintainer myself, I would prefer the second way. Do you have some other application I could look at for inspiration that generates completions as a build time step?

**Comment by KSXGitHub** [comment]
For the first method (which is pretty straightforward), there are [deno](https://github.com/denoland/deno) and [dvm](https://github.com/justjavac/dvm).

For generating completion files ahead of time, there are [strip-ansi-cli](https://github.com/KSXGitHub/strip-ansi-cli), [pretty-exec](https://github.com/KSXGitHub/pretty-exec), and [sane-fmt](https://github.com/sane-fmt/sane-fmt) (my projects), they all have NAME and NAME-bin AUR packages (generated and deployed automatically by the GitHub CI). I didn't use `build.rs` script for these projects but it should be simple (I'll probably switch to `build.rs` soon).

As for where to place completion files:
  * bash: `${pkgdir}/usr/share/bash-completion/completions/${pkgname}`
  * zsh: `${pkgdir}/usr/share/zsh/site-functions/_${pkgname}` (note: there is a completion cache that must be rebuilt by the user)
  * fish: `${pkgdir}/usr/share/fish/completions/${pkgname}.fish`
  * I don't use powershell and elvish so I don't know where to place them, but it's still a good idea to allow users to download completion files for these shells.

**Comment by KSXGitHub** [comment]
**Update:** I have tried using `build.rs` to generate completion files, but it turns out that `build.rs` cannot import the main crate. There is [a `build.rs` example](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.gen_completions) but it uses `include!()` which would require miniserve to change almost everything. So I guess that the only way left to generate completion file ahead of time is my method:

```toml
# to allow other binary commands to import
[lib]
name = "miniserve"
path = "./src/lib.rs" # rename main.rs to lib.rs, make `main` function public, re-export `args::CLIArgs`

# main application
[[bin]]
name = "miniserve"
path = "./src/main.rs" # create a new main.rs file that just calls `miniserve::main()`

# script to generate completion files
[[bin]]
name = "miniserve-completions"
path = "..."
```

Now you can run `cargo run --bin=miniserve-completions` to generate completion files.
