### ISSUE TITLE
Ability to ship miniserve with the files built to the binary

### ISSUE THREAD

**Issue by paulocsanz** [svenstaro/miniserve#385]
Hello, 

Sometimes I need to serve static files known at compile time, so I generally just make my boilerplate server with include_dir! to bundle the files to the binary. So I can deploy the binary by just uploading it, instead of having external runtime dependencies.

Allowing files to be bundled at compile time not only makes it easier to deploy by producing a single, independent, binary that just works. But it also avoids runtime filesystem access delay, it removes the need for security considerations at runtime, since only what was provided at compile time is available. And remove errors possible at runtime, if something is changed in the filesystem.

I know this is not the best feature to ask for a binary project, and some thought must be made to include it, since sometimes you want both ways (compile time files and dynamic files). But I would very much like to have this feature in current solutions instead of a parallel version that doesn't have the other features miniserve has.

**Comment by svenstaro** [comment]
How about this: You get the ability to append a tar or zip to any finished miniserve binary and it'll serve those files inside the appended archive?

It could look like this:

    cat miniserve myfiles.tar.gz > miniserve_with_myfiles

Then you could just give people your resulting `miniserve_with_myfiles` binary which has those bundled files permanently appended.
