### ISSUE TITLE
Missing subfolder path in generated links when using Apache reverse proxy

### ISSUE THREAD

**Issue by johnchristopher** [svenstaro/miniserve#387]
Hello,

I am putting miniserve behind an Apache reverse proxy, on localhost and using subfolders (not subdomains).

`http://localhost/miniserve/` display the miniserve root web page but links in the page are missing the subfolder path used in the host URL.

```shell
ls /home/pi/webroot
folder1
folder2
```

Links in miniserve page are in the form of `http://localhost/folder1/` but I expect it to be in the form of `http://localhost/miniserve/folder1/`. Accessing directly `http://localhost/miniserve/folder1/` behaves as expected.

Modifications to the default apache2.conf are as follow:
```conf
ProxyPreserveHost On
ProxyPass /miniserve/ http://127.0.0.1:8080/
ProxyPassReverse /miniserve/ http://127.0.0.1:8080/
```

I am running miniserve like this:
```shell
./miniserve \
  --enable-tar \
  --enable-zip \
  --color-scheme Squirrel \
  /home/pi/webroot
```

Is miniserve removing/ignoring path from the host when generating links or am I missing some additional apache2 settings ?

Thanks ^^

edit: I tested the apache2.config against a different webserver and it behaves according to my expectations:
```shell
pi@localhost: ~/webroot $ python -m SimpleHTTPServer 8080
```

edit2: Just saw this PR https://github.com/svenstaro/miniserve/pull/208 about the issue.

**Comment by svenstaro** [comment]
Fixed by #728.
