### ISSUE TITLE
[feature suggestion] show the IP address from all interfaces

### ISSUE THREAD

**Issue by Grabber** [svenstaro/miniserve#422]
miniserve could print the IP address from all interfaces it's listening on:

*http-server*
```
lvmc@Luizs-MacBook-Pro ~ % http-server
Starting up http-server, serving ./public
Available on:
  http://127.0.0.1:8081
  http://192.168.0.101:8081
  http://192.168.15.7:8081
Hit CTRL-C to stop the server
```

*miniserve*
```
lvmc@Luizs-MacBook-Pro Desktop % miniserve -q -v .
miniserve v0.10.3
00:32:55 [INFO] Starting 16 workers
00:32:55 [INFO] Starting "actix-web-service-[::]:8080" service on [::]:8080
00:32:55 [INFO] Starting "actix-web-service-127.0.0.1:8080" service on 127.0.0.1:8080
Serving path /Users/lvmc/Desktop at http://[::]:8080, http://127.0.0.1:8080

Quit by pressing CTRL-C
```

It helps a lot to share the links on local networks.

**Comment by Grabber** [comment]
![Screen Shot 2021-01-02 at 01 50 40](https://user-images.githubusercontent.com/15731/103450977-f1300f80-4c9c-11eb-8c37-0111b0defb27.png)

I think it's also interesting to support the QRCODE per listening IP address, sharing will be much easier.

**Comment by bigdogs** [comment]
listing ip addresses of all interface sounds very usefully,

**Comment by Grabber** [comment]
@bigdogs, yes!

maybe auto-refreshing the listening IP addresses when the interface assignments change is also a good idea.

**Comment by superiums** [comment]
good ieda. it's very usefull. wish update.

**Comment by chromer030** [comment]
Yes, Please add a feature to show external IP on verbose mode
