### ISSUE TITLE
[help] binary built from cargo is much bigger than distribution version

### ISSUE THREAD

**Issue by bigdogs** [svenstaro/miniserve#433]
on macos, 
binary built from "cargo build --release" is 4.4M,  
binary on link of readmy only 871kb
can someone explain that why such a big difference?

**Comment by svenstaro** [comment]
The trick is to run upx --lzma on it and strip the binary. You can check how the release is built in the files under .gitlab.

**Comment by bigdogs** [comment]
Thank you!
