### ISSUE TITLE
how to complier for openwrt route?

### ISSUE THREAD

**Issue by carlsue** [svenstaro/miniserve#446]
how to complier for openwrt route? 
eg. mipsle cpu arch?

**Comment by svenstaro** [comment]
Would it help you if I provided MIPSEL and similar architectures prebuilt?

**Comment by carlsue** [comment]
> Would it help you if I provided MIPSEL and similar architectures prebuilt?

yes ,i want to setup a nas server with my router(have changed os to openwrt 19)

**Comment by svenstaro** [comment]
Check the pre-compiled binaries of the new v0.11.0. Do any of those work for you?

**Comment by carlsue** [comment]
> Check the pre-compiled binaries of the new v0.11.0. Do any of those work for you?
can run,but no response,and netstat show no listen
![image](https://user-images.githubusercontent.com/17507066/109980717-25768980-7d3b-11eb-95f0-532645d63873.png)

**Comment by svenstaro** [comment]
That's weird. Which exact MIPS architecture did you try? Can you show me `uname -a`?

**Comment by carlsue** [comment]
> That's weird. Which exact MIPS architecture did you try? Can you show me `uname -a`?

Linux xxx 3.14.79 #0 SMP Fri Feb 1 20:24:57 2019 mips PandoraBox

rom address:
https://downloads.pangubox.com:63443/pandorabox/19.02/

**Comment by svenstaro** [comment]
Which of the MIPS-based downloads did you try?

**Comment by carlsue** [comment]
> Which of the MIPS-based downloads did you try?
this one (miniserve-v0.11.0-mipsel-unknown-linux-musl)

my cpu is mt7621
cpu model               : MIPS 1004Kc V2.15
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 1

**Comment by svenstaro** [comment]
Can you post the output of lscpu?

**Comment by carlsue** [comment]
> Can you post the output of lscpu?

Architecture:        mips
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
BogoMIPS:            583.68

**Comment by svenstaro** [comment]
Can you test this one? It's compiled against the gnu ABI instead of musl.
[miniserve.zip](https://github.com/svenstaro/miniserve/files/6095392/miniserve.zip)

**Comment by carlsue** [comment]
> Can you test this one? It's compiled against the gnu ABI instead of musl.
> [miniserve.zip](https://github.com/svenstaro/miniserve/files/6095392/miniserve.zip)

[root@xx:/tmp]#./miniserve
-ash: ./miniserve: not found
[root@xx:/tmp]#bash miniserve
-ash: bash: not found
[root@xx:/tmp]#sh miniserve
miniserve: line 1: syntax error: unexpected "("
[root@xx:/tmp]#

**Comment by aliemjay** [comment]
Can you post the output of:
$ ls /lib/ld-* /lib/libc.*
$ ldd _[miniserve binary]_

**Comment by carlsue** [comment]
> Can you post the output of:
> $ ls /lib/ld-* /lib/libc.*
> $ ldd _[miniserve binary]_

/lib/ld-uClibc-1.0.31.so  /lib/ld-uClibc.so.1       /lib/libc.so.1
/lib/ld-uClibc.so.0       /lib/libc.so.0

no ldd bin file

**Comment by aliemjay** [comment]
> /lib/ld-uClibc-1.0.31.so /lib/ld-uClibc.so.1 /lib/libc.so.1
> /lib/ld-uClibc.so.0 /lib/libc.so.0

Your C library is uClibc, and the binaries provided are for musl and glibc only. Your rom seems a bit old since openwrt switched from uclibc to musl as the default since v17.0

I don't know if @svenstaro would provide the compiled binaries, but rust has tier 3 support for mipsel-unknown-linux-uclibc which is described as "may not work"
https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by svenstaro** [comment]
I don't really want to support tier 3 stuff.

**Comment by svenstaro** [comment]
I'll close this for the time being as it's a system I can't really support. Please try to compile miniserve yourself and report back if it works. Alternatively, you can try updating your system, and then one of the provided binaries should work for you.
