### ISSUE TITLE
How about a QR-code in the terminal?

### ISSUE THREAD

**Issue by FrontMage** [svenstaro/miniserve#45]
I mean it would be handy for phones to access. Maybe a QR-code in the HTML page as well?

**Comment by svenstaro** [comment]
Yeah, I think that'd be cool and helpful.

**Comment by boastful-squirrel** [comment]
That's a cool idea. How would we decide on which IP the QR-code would point ? An argument like `qr-code=my.public.ip.address` maybe ?

**Comment by svenstaro** [comment]
Maybe we can figure out the local domain (from /etc/resolv.conf `domain`) and hostname and construct the full local hostname that way?

**Comment by whmountains** [comment]
I think we could borrow a lot from [Quair](https://crates.io/crates/qair).  Specifically local IP address detection and how to display a QR code for displaying in the terminal.

[qrcodegen](https://crates.io/crates/qrcodegen) looks like a great option for generating the SVG file for use in the web interface.

**Comment by svenstaro** [comment]
Yeah, quair seems really neat. I wish it were a library. The [IP stuff](https://code.willemp.be/willem/qair/src/branch/master/src/myip.rs#L10) seems easy enough.

**Comment by H-M-H** [comment]
There also is https://github.com/kennytm/qrcode-rust which does image, svg and text encoding of QR-codes.

**Comment by svenstaro** [comment]
We now have a QR code in the HTML. We don't yet have one on the terminal but I'd be open for that option, too.

**Comment by wyhaya** [comment]
@svenstaro 

If the user uses the `-i` option, the content of the QR code should be `http://{-i}:{-p}`.

If the user does not use the `-i` option, then search for `interfaces`, then the content of the QR code should be `http://{interface}:{-p}`.

Looks like this:

```
miniserve v0.7.0
Serving path .../miniserve at http://[::]:8080, 
http://127.0.0.1:8080
██████████████      ██  ██████████  ██████████████
██          ██  ██  ██  ██  ██      ██          ██
██  ██████  ██        ██  ██████    ██  ██████  ██
██  ██████  ██  ██        ██  ██    ██  ██████  ██
██  ██████  ██  ██  ██████      ██  ██  ██████  ██
██          ██  ████████      ████  ██          ██
██████████████  ██  ██  ██  ██  ██  ██████████████
                  ██  ██  ████
  ██  ████  ██████████        ██  ██  ██████  ██
██    ██  ██      ████          ██    ████  ██████
██  ████    ██    ██  ██      ██    ██████  ██  ██
██  ██    ██  ██  ██  ██████            ██      ██
██        ████  ██  ████    ████  ██      ██    ██
██████  ████    ██      ████    ██  ██      ██████
████████  ████████████████    ██  ██    ████    ██
████  ████      ████████  ████  ████    ██      ██
      ██    ██    ██    ██  ██████████████  ██  ██
                ████    ██  ██  ██      ██    ████
██████████████  ██  ██  ██      ██  ██  ████  ████
██          ██            ██    ██      ████  ██
██  ██████  ██  ████      ██  ████████████  ████
██  ██████  ██  ████████    ██      ██  ████    ██
██  ██████  ██    ██  ██    ██████          ████
██          ██  ████  ██  ████  ████      ██████
██████████████      ██████  ████    ██████████████
Quit by pressing CTRL-C
```

It should be noted that how to print the QR code when using multiple `-i`? Or print multiple QR codes?

**Comment by svenstaro** [comment]
Hm yeah, I wonder. I think multiple QR codes would be weird. Maybe only print the IPv4 QR code to be safe?

**Comment by wyhaya** [comment]
If only one QR code is printed, then when we run:
`miniserve . -i 127.0.0.1 -i 192.168.0.40` 
What should be the content of the QR code?

**Comment by svenstaro** [comment]
Haha, good point! Well, maybe it does make a good deal of sense to print one QR code per listening interface, then.
