### ISSUE TITLE
.tar.gz and .tar

### ISSUE THREAD

**Issue by JqrSo** [svenstaro/miniserve#451]
![`(LJE7 8%VR6UWZAF4%IVML](https://user-images.githubusercontent.com/52708641/108618750-8fe61a80-745b-11eb-9590-7ab0dd54ed81.png)

Can you turn on only one of these two buttons
![tar](https://user-images.githubusercontent.com/52708641/108618965-fe77a800-745c-11eb-8212-a35f87789220.jpg)
![tar gz](https://user-images.githubusercontent.com/52708641/108618969-02a3c580-745d-11eb-88af-65cde0a46c2f.jpg)

FLAGS:
           -r, --enable-tar
                      Enable tar archive generation

**Comment by svenstaro** [comment]
An additional flag would make sense, I guess.

**Comment by JqrSo** [comment]
> An additional flag would make sense, I guess.
我写了个bat
![QQ录屏20210228134854](https://user-images.githubusercontent.com/52708641/109409378-23c06500-79cd-11eb-9ca9-37f925ea737a.gif)
`@echo off
setlocal enabledelayedexpansion

for /f "tokens=2 delims=:" %%j in ('ipconfig ^| find /i "IPv4"') do (
set url=%%j
set ip=-i !url: =! !ip!
start http://!url: =!:8080
)

D:\app\miniserve-v0.11.0-x86_64-pc-windows-msvc.exe -D -r -q -u !ip! %1`

**Comment by JqrSo** [comment]
> > An additional flag would make sense, I guess.
> 
> I wrote a bat.
> To achieve this effect
> 
> ![QQ录屏20210228134854](https://user-images.githubusercontent.com/52708641/109409378-23c06500-79cd-11eb-9ca9-37f925ea737a.gif)
> 
> code
> 
> @echo off
> setlocal enabledelayedexpansion
> for /f "tokens=2 delims=:" %%j in ('ipconfig ^| find /i "IPv4"') do (
> set url=%%j
> set ip=-i !url: =! !ip!
> start http://!url: =!:8080
> )
> D:\app\miniserve-v0.11.0-x86_64-pc-windows-msvc.exe -D -r -q -u !ip! %1

**Comment by svenstaro** [comment]
This has been implemented by @deantvv!
