### ISSUE TITLE
Architecture not specified for release binaries

### ISSUE THREAD

**Issue by Celti** [svenstaro/miniserve#46]
The three release binaries are all for x86-64, but this is not specified anywhere. With the increasing prevalence of ARM-based systems even in the Windows world (e.g. various Snapdragon-based laptops) the releases page should at _least_ list architecture (e.g., `miniserve-linux-x86_64`). Long-term, using a platform like [trust](https://github.com/japaric/trust) on Travis to test and generate releases for multiple architectures seems wise.

**Comment by svenstaro** [comment]
Good point.
