### ISSUE TITLE
Consider send 401 instead of 403 when username or password is incorrect.

### ISSUE THREAD

**Issue by weiby3** [svenstaro/miniserve#47]
If you didn't enter the correct username or password, the browser will save them and send them to miniserver even when you force refresh the page. And you can't find anyway to logout.

**Comment by svenstaro** [comment]
Yes, I believe that makes sense.

**Comment by svenstaro** [comment]
Can you test master for me on your expected behavior and re-open if this problem remains?

**Comment by weiby3** [comment]
It solved the problem. Thanks.

**Comment by svenstaro** [comment]
Sweet! Will make a release soon.
