### ISSUE TITLE
Consider turning on transfer compression

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#497]
actix-web has a ready-to-go [compress middleware](https://docs.rs/actix-web/3.3.2/actix_web/middleware/struct.Compress.html). I currently don't really see any downsides with turning that on. Will have to do a little benchmarking to see whether it's ok to generally turn this on.

**Comment by deantvv** [comment]
After reading NGINX document of compression [link](https://docs.nginx.com/nginx/admin-guide/web-server/compression/), here is some of my thoughts from it.

> By default, NGINX compresses responses only with MIME type text/html.

This is clear now why the test benchmark in #523 looks so bad, and NGINX by default do not enable this except text/html.

NGINX tried to work around this by introducing a new option called `gzip_static`.
> Note that the gzip_static directive does not enable on-the-fly compression. It merely uses a file compressed beforehand by any compression tool.

In this option, you need to provide a gzip version of the file before the request comes in. This will save network bandwidth and also not increase CPU load by a lot (only a simple directory looking for the compressed file). 

It seems to me that both options may be overkilled to miniserve. Especially the first line of the README for miniserve is "For when you really just want to serve some files over HTTP right now!".
