### ISSUE TITLE
Just let you know that I submitted miniserve-bin to ArchLinux's AUR

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#50]
I have just submitted [miniserve-bin](https://aur.archlinux.org/packages/miniserve-bin/) to the AUR, you may want to include this in your README.md as an installation method (or not :smile: ).

~~I'm also willing to hear any update from you about new versions (so that I can update my AUR).~~

**Comment by svenstaro** [comment]
Thank you, though I'm not really sure what benefit that provides except for slightly quicker installation time every now and then.
