### ISSUE TITLE
[feature request] add the ability to create directory

### ISSUE THREAD

**Issue by david0u0** [svenstaro/miniserve#502]
Hi,

I've recently started use miniserve and think it would be great to have a button/api to create a directory, but after searching for a while it seems this is currently not available.

With this feature, users can easily write a script to "uplaod a directory recursively". This can be toggle by command line flag, such as `--enable-mkdir`

If this feature is desirable, I'd like to help submit a PR. Thanks again for the great crate

**Comment by svenstaro** [comment]
Yeah sounds good. I'd accept a PR for that.
