### ISSUE TITLE
Rework colors

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#51]
Currently I'm not super happy with how everything looks. It has a pale color palette without good contrast. It should have better contrast.

**Comment by boastful-squirrel** [comment]
Should be easy, do you have a colorscheme or an application you like design-wise ?

**Comment by svenstaro** [comment]
I actually kinda like that colorscheme. Actualllly how about colorscheme support? We could provide a bunch of colorschemes. The few bytes won't make it too bloaty and another added CLI option won't kill us.

Yeah but generally I also want a more contrasted default color scheme that still looks clean but just has better contrast than the current one.

**Comment by boastful-squirrel** [comment]
Sure, great idea. I'll be on it then ;)

**Comment by svenstaro** [comment]
Yes, absolutely go for hard coding them.

**Comment by svenstaro** [comment]
Maybe actually in the form of having a different CSS template files? I'm not sure which would be better.

**Comment by boastful-squirrel** [comment]
If we only change colors, I think the first option is the easiest. If we want to have actual themes and not only color schemes, the latter option is the best.

I'll start with the first one, we'll see how it goes

**Comment by svenstaro** [comment]
Sounds good.

**Comment by boastful-squirrel** [comment]
I'm doing good progress. I'll create the PR once I created enough themes. 

Here's my version of Zenburn:
<img width="1139" alt="Screenshot 2019-03-26 at 23 02 22" src="https://user-images.githubusercontent.com/47121073/55036594-6a57f880-501b-11e9-8f31-0efba1dcb8af.png">

Everything can be customized if you don't like a color, I already parametrized all the CSS.

**Comment by svenstaro** [comment]
While you're at it. I somehow really don't like the way the date is
formatted under Last modification. It seems weirdly spaced out. Can you
play around with that as well?

**Comment by boastful-squirrel** [comment]
Sure, how would you want it to be ?

**Comment by svenstaro** [comment]
I honestly don't know :P I'd probably play around with it a bit and look at how other software represents the dates.

**Comment by boastful-squirrel** [comment]
OK, I'll look at this.

In the meantime, I came up with that:
<img width="318" alt="Screenshot 2019-03-26 at 23 28 34" src="https://user-images.githubusercontent.com/47121073/55037699-e6a00b00-501e-11e9-91e4-447d9312e0ca.png">

**Comment by svenstaro** [comment]
I like the a lot more than what we have currently! Also try putting the
time just in front of the date and see how it looks.

**Comment by boastful-squirrel** [comment]
I'll keep experimenting :)

By the way, instead of doing it a CLI argument, I did a theme chooser in pure CSS, and the theme has become a query parameter. Since theme is really up to the client, I found it wierd to set it at CLI-level, kind of like sorting.

Still a prototype, but it looks like this at the moment:
<img width="1200" alt="Screenshot 2019-03-27 at 23 49 30" src="https://user-images.githubusercontent.com/47121073/55117471-419f3400-50eb-11e9-9264-3441cb2d80ef.png">

Note that all the colors depends on which theme is set.

**Comment by svenstaro** [comment]
You make a very good point and I agree.

**Comment by boastful-squirrel** [comment]
I'm currently trying to find an elegant way to "instanciate" a theme. The struct associated to a theme is quite big, and right now I did something like this: https://gist.github.com/boastful-squirrel/dcb4105fe4cef910355a4eb9de7c9c12 which I find a bit too verbose.

Taking an `&[&str]` as parameter of `Theme::new()` would probably less verbose, though I don't think that's a very clean way of handling such a case.

**Comment by svenstaro** [comment]
Why use a constructor at all? Why not just put a few preconstructed themes
in the module and call it a day? I don't really see a need for new() here.

**Comment by boastful-squirrel** [comment]
That's also a solution, indeed
