### ISSUE TITLE
Build of miniserv 0.3.1 fails on all macOS versions

### ISSUE THREAD

**Issue by fxcoudert** [svenstaro/miniserve#53]
Build of miniserv 0.3.1 fails on all macOS versions (https://github.com/Homebrew/homebrew-core/pull/38306) with:

```
   Compiling literalext v0.1.1
error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/literalext-0.1.1/src/lib.rs:19:37
   |
19 | #![cfg_attr(feature = "proc-macro", feature(proc_macro))]
   |                                     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `literalext`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `miniserve v0.3.1 (/private/tmp/miniserve-20190326-39556-106jom/miniserve-0.3.1)`, intermediate artifacts can be found at `/private/tmp/miniserve-20190326-39556-106jom/miniserve-0.3.1/target`

Caused by:
  build failed
```

**Comment by svenstaro** [comment]
You have to use nightly to build it I'm afraid.

**Comment by fxcoudert** [comment]
Nightly rust? If that's the case, then we can't ship that version in Homebrew. And if that is a general policy that `miniserve` released versions cannot build with latest `rust` releases, then we should drop it altogether.

**Comment by svenstaro** [comment]
That's a pity. Yeah, we decided to use maud which necessitates the use of nightly Rust. Is it an option for you to rely on the prebuilt binaries that miniserve automatically builds for every release?

**Comment by fxcoudert** [comment]
No, Homebrew core only ships software that builds from source within Homebrew CI. When are the features you need supposed to land in released version of rust?

**Comment by svenstaro** [comment]
Once all of these are on stable: https://github.com/lfairy/maud/issues/17

Probably many months :P 

Is it a possibility for you to grab a prebuilt rust nightly as part of the build for miniserve with which to build miniserve? That sounds like a reasonable middle-ground.

**Comment by fxcoudert** [comment]
We allow bootstrap processes, in some cases, for formulas where no other compiler exist (`go` is an example) and that have wide usage. For `miniserve` it doesn't really fit that case, and the usage (57 installs in three months) doesn't warrant it. Sorry.

We'll keep the old version for now, but if it gets stuck too long (or if the old version has security issues), it will be a candidate for removal.

Otherwise you can maintain it in your own tap, which means it's much more flexible what you can do :)

**Comment by svenstaro** [comment]
Yeah, I understand. At any rate, Mac users can always use the provided binaries that we ship for the time being. It will run on stable at _some_ point.

**Comment by svenstaro** [comment]
canonicalize
