### ISSUE TITLE
Can we specify the route digit?

### ISSUE THREAD

**Issue by wizyoung** [svenstaro/miniserve#533]
Currently we can use `--random-route` to set the generated random 6-hexdigit route. Is there a method to manually specify the route digit?

**Comment by aliemjay** [comment]
Actually there is a PR for this feature #208

**Comment by 4920441** [comment]
Hmmm that issue bothers me as well, since behind a reverse-proxy miniserve makes lots of problems because the first subdir changes everytime, so the wrong url is called (the wrong subdir)

**Comment by svenstaro** [comment]
This is now fixed by #728! :D
