### ISSUE TITLE
Failed to resolve path to be served

### ISSUE THREAD

**Issue by zxjack** [svenstaro/miniserve#544]
● miniserve@-root-downloads.service - miniserve for -root-downloads
     Loaded: loaded (/etc/systemd/system/miniserve@.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2021-06-09 10:31:27 CST; 2s ago
    Process: 128533 ExecStart=/usr/bin/miniserve -p 2345 -- /root/downloads (code=exited, status=0/SUCCESS)
   Main PID: 128533 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out

Jun 09 10:31:27 cloud systemd[1]: Started miniserve for -root-downloads.
Jun 09 10:31:27 cloud miniserve[128533]: 02:31:27 [ERROR] Failed to resolve path to be served
Jun 09 10:31:27 cloud miniserve[128533]: 02:31:27 [ERROR] caused by: Permission denied (os error 13)
Jun 09 10:31:27 cloud systemd[1]: miniserve@-root-downloads.service: Succeeded.

**Comment by jcaesar** [comment]
Try this:
```bash
$ sudo env EDITOR=$EDITOR systemctl edit miniserve@-root-downloads
```
And add a:
```
[Service]
DynamicUser=no
ProtectHome=no
```

But honestly, the fact that you have a downloads folder in your `~root` worries me, and the fact that you want to serve files from your root's home directory worries me even more. I think the two protections are enable for a good reason.

(Side note: I'm not a project contributor.)

**Comment by svenstaro** [comment]
Yeah so as @jcaesar pointed out, this is due to the strict security-minded defaults of the default service file that's shipped with miniserve. I actually recommend that you don't mess around with that too much for security reasons but the provided fix should work in your case.

**Comment by svenstaro** [comment]
I'm closing this for now as the OP appears to have stopped replying. If you guys have any suggestions on how to improve this or inform users better, I'd appreciate an issue as a follow-up or even a PR.
