### ISSUE TITLE
Cannot retrieve file with \ in name

### ISSUE THREAD

**Issue by jcaesar** [svenstaro/miniserve#545]
I was trying to reproduce a bug where files with `#` in the name wouldn't be served by an older version (that one seems fixed), and found that current master turns `\` into `/`.

I looked into the source a bit to find out why, remembered the whole set of problems with Paths and strings and `to_string_lossy` and promptly bailed. (Of course, it won't serve a file like `touch "$(echo 日本語 | iconv -f utf-8 -t shift-jis)"` either, and that's probably not easy to fix. I'm not sure that's common enough a problem to tackle.)

**Comment by aliemjay** [comment]
> found that current master turns `\` into `/`
On linux this shouldn't happen!

The utf-8 problem is due to the limitations of `actix-web/actix-files`, which assume the request URLs to be utf-8 encoded. The `to_string_lossy` is used here to render the file name to the user, not to form URLs.

**Comment by jcaesar** [comment]
> On linux this shouldn't happen!

I'm sure it shouldn't. I assure you it is. ;)
(Ah yeah, I should have mentioned, I'm on a glibc-based Linux, rustc 1.52.1, miniserve da02932.)

> The to_string_lossy is used here to render the file name to the user, not to form URLs.

I'm most likely misunderstanding the code here...
https://github.com/svenstaro/miniserve/blob/da029329d02bf3f0f75007f2c02f4425d3c2f86b/src/listing.rs#L262
https://github.com/svenstaro/miniserve/blob/da029329d02bf3f0f75007f2c02f4425d3c2f86b/src/listing.rs#L270-L273
https://github.com/svenstaro/miniserve/blob/da029329d02bf3f0f75007f2c02f4425d3c2f86b/src/listing.rs#L295-L299

**Comment by aliemjay** [comment]
Hmm, you're right, we're using `utf8_lossy` to form file URLs. I should've checked this (I authored this code). But that is not the problem after all; the he problem is with `actix-web`

**Comment by aliemjay** [comment]
the backslash `\` seems to be a browser problem. The URL in the web page is correct (`href="/a\b/"`) but firefox interprets it as `/a/b`. `curl` works fine here.

This can be easily fixed by using percent-encoding for `\`.

**Comment by svenstaro** [comment]
Fixed in master thanks to @Jikstra! :)
