### ISSUE TITLE
visit the url path without suffix

### ISSUE THREAD

**Issue by zidoshare** [svenstaro/miniserve#555]
Some special suffixes can be specified through the http header，like this:

server shell:
```shell
$ echo '{"hello":"world"}' > config.json
$ echo '<html><head><title>demo</title></head></html>' > demo.html
$ miniserve
```
client shell:
```shell
$ curl -H "application/json" http://localhost:8080/config
{"hello":"world"}
$ curl -H "text/html" http://localhost:8080/demo
<html><head><title>demo</title></head></html>
```

This can help me with some simple tests.

**Comment by svenstaro** [comment]
I think this would be rather confusing and I currently don't really see the use case. Also, in almost 2 years, there didn't seem to be a lot of interest here. I'm going to close this for the time being. If you can make a good case for this, I might reconsider.
