### ISSUE TITLE
Bump actix-web to beta versions

### ISSUE THREAD

**Issue by aliemjay** [svenstaro/miniserve#581]
The beta channel is pretty stable and used by many i production, it supports tokio v1.0 and would fix many open issues here.

And  as I see v4 is nowhere in the near future, I think it is reasonable to switch to beta.

I'm happy to submit a PR if it is approved @svenstaro .

**Comment by svenstaro** [comment]
I'm generally fine with this. Which issues would it fix?

**Comment by aliemjay** [comment]
#462 and enable us to easily implement #275 #474 #458

**Comment by svenstaro** [comment]
Alright well go right ahead then.
