### ISSUE TITLE
Update README to refelect the new binding behavior

### ISSUE THREAD

**Issue by aliemjay** [svenstaro/miniserve#589]
> For convenience reasons, miniserve will try to bind on all interfaces by default (if no -i is provided). It will also do that if explicitly provided with -i 0.0.0.0 or -i ::. In all of the aforementioned cases, it will bind on both IPv4 and IPv6.

Now `-i 0.0.0.0` will bin to IPv4 only, and `-i ::` to IPv6.

**Comment by svenstaro** [comment]
@aliemjay Wanna write a short bit about this on the README?
