### ISSUE TITLE
Maybe allow uploading?

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#6]
Perhaps it would be useful to also allow users to upload files. Investigate.

**Comment by lukedoomer** [comment]
yes please implement it. uploading feature is important.

**Comment by amitbha** [comment]
Agree.
I use it to transfer files from pc to phone. If support upload, then between pc and phone. 😌

**Comment by boastful-squirrel** [comment]
I am currently on it. Let's see if I can do it. This will be very simple and straightforward, since we don't have javascript and serve static HTML files. Once this issue done, I agree that we should start splitting the project into multiple files.

**Comment by svenstaro** [comment]
Drag and drop and alternatively a classic upload form would be nice I think.

**Comment by vojta7** [comment]
Hi,
I started experimenting with file upload, because this issue seems abandoned. I hope I will have working version by tomorrow ( just few finishing touches ).

**Comment by svenstaro** [comment]
@vojta7 awesome to hear!
