### ISSUE TITLE
give a solid_route

### ISSUE THREAD

**Issue by hz0ne** [svenstaro/miniserve#600]
every time to reboot the server, the link http://9.189.2.201:8080/a7d2c7/ with random route will change adress.
this func is  really good to protect data
but, how to give a solid_route, make server reboot more convenient?

**Comment by svenstaro** [comment]
Would this help you? https://github.com/svenstaro/miniserve/pull/579

**Comment by hz0ne** [comment]
> Would this help you? #579
sorry, that random route make server address change wtih reboot miniserve，#579 seem just make random route function sepreat from server local path

**Comment by svenstaro** [comment]
Isn't what you want just a pre-defined path prefix? I really don't see how that's different from #579.

**Comment by svenstaro** [comment]
Fixed by #728.
