### ISSUE TITLE
Packaging for Windows

### ISSUE THREAD

**Issue by nagromc** [svenstaro/miniserve#602]
Really nice application 👍 

You should publish `miniserve` on [Chocolatey](https://chocolatey.org/) and [Scoop](https://scoop.sh/) to facilitate the deployment and upgrades.

**Comment by Dialga** [comment]
I've requested this in scoop too https://github.com/ScoopInstaller/Main/issues/2679.

**Comment by aathif394** [comment]
While we're at it, it would be nice to add it to winget as well

**Comment by svenstaro** [comment]
This is now in scoop (thanks @Dialga) and I've looked into winget and choco but it seems like I'm going to need to maintain some kind of package file in the repo then. I'd be generally willing to do that (and to set up automation for pushing the package) if someone can do the initial work and make a PR with a nupkg file that'll build on Windows.

I've also documented the scoop way to install miniserve in the README. Overall, this is already pretty Windows-friendly with three ways to run it on Windows (Docker, direct exe and scoop). Do we need more? Let me know what you think.

**Comment by Dialga** [comment]
I only use scoop, but I'm sure it doesn't hurt to expand the number ways to install miniserve on Windows, if someone sends in a PR.

**Comment by kimwonj77** [comment]
I just submitted winget package PR. but it is blocked by Winget's issue. (msvc build requires msvc redist as dependency. and it doesn't supported on winget for now. See microsoft/winget-pkgs#101652)

Also, there's automate github actions for winget. one of them is https://github.com/vedantmgoyal2009/winget-releaser
Once winget solves the problem, It would be nice to use those actions for automatic release.

**Comment by svenstaro** [comment]
I'm fine with adding some automation for this, yes. Thanks for adding this to winget. Please make sure to make a follow-up MR to the README to document this new installation method. You could also try to add the action to the release workflow. :)

**Comment by svenstaro** [comment]
@kimwonj77 Now that we're linking CRT statically, I think the issue should be unblocked. Could you check?

**Comment by kimwonj77** [comment]
I checked that in my local sandbox and yes, it works. (with latest build artifacts from github.)
<details><summary>With latest master build</summary>
<p>
<img src="https://user-images.githubusercontent.com/95566897/235031650-2c1138ff-2a68-426a-9dad-118dfd0882f3.png"/>
</p>
</details> 
<details><summary>With 0.23.0</summary>
<img src="https://user-images.githubusercontent.com/95566897/235031807-11c76e44-2240-43c0-8740-12dcf9fa62e9.png"/>
</p>
</details>
I'm waiting for new release!

**Comment by svenstaro** [comment]
Super nice. Here's 0.23.2. Can we consider this issue done then?

**Comment by kimwonj77** [comment]
Maybe. At least https://github.com/microsoft/winget-pkgs/pull/103754 is merged. And we could automate the PR after all.

**Comment by kimwonj77** [comment]
It's merged now and it works great on my windows machines! It's safe to close now.

Also, If you want to setup auto-release on winget packages, try using https://github.com/vedantmgoyal2009/winget-releaser
However, it needs to use github account/token (as winget-pkgs are based on GitHub PR). If don't want to give the access to actions on your primary account, you can make some 'bot account' for this.

**Comment by svenstaro** [comment]
I might add the auto releasing thing. With scoop, I think someone updates the package manually with a PR. That seems to work rather well. Would that be possible in this case as well if I don't get to automate it? I will still look into it, however.

**Comment by kimwonj77** [comment]
Well, if someone keep interested in, package(s) will be updated (via manually or automatically by someone).  It's like a third-party scoop packaging.

**Comment by svenstaro** [comment]
Thanks. At any rate, I think we can consider this particular request closed now. :)
