### ISSUE TITLE
Remove unwrap()'s

### ISSUE THREAD

**Issue by boastful-squirrel** [svenstaro/miniserve#61]
We have some places in the code where we call unwrap() (4 to be precise).

Maybe we could replace those with unwrap_or* (default value, actual error, etc, depending on the case) for unwrap()'s happening outside the main() method, and as for the ones happening in the main(), printing a nice error message with the logger + exiting instead of panicking.

This has been suggested in Reddit's "what's everyone working on this week": https://www.reddit.com/r/rust/comments/bapows/whats_everyone_working_on_this_week_152019/ekdt4ls

**Comment by svenstaro** [comment]
Yeah, that'd be a good effort.

**Comment by boastful-squirrel** [comment]
I'll be on it soon. I'll also profit in this for migrating the auth errors to errors.rs, and use failure.

**Comment by boastful-squirrel** [comment]
Just one quick question, do you mind having an enum with all miniserve's error kind, or do you want them to be split like right now, aka `CompressionErrorKind`, `UploadErrorKind`, etc ? In the latter case, I think I need to implement `Fail`, `Display`, etc, for all those enums, so some copy/paste. Having a single enum allows to implement it once for good, but that's 1 quite big enum. Your call  :)

Just to highlight how it would look, here's an example: https://gist.github.com/boastful-squirrel/64b18f90a706fb285b395b3d9a269363

PS: there might be a third solution, that would allow to have separate enums, but only 1 implementation, but sadly I can't figure out how...

**Comment by boastful-squirrel** [comment]
Also, I fixed the check for the auth string according to the RFC:

- Username can be 255 character long maximum and cannot contain `:`
- No restriction on the password

**Comment by svenstaro** [comment]
Ok so honestly I'm thinking hard about both ways and I think I'm entirely balanced concerning my opinion on the matter. For one, it seems nice to have separate errors for separate parts of the application but then again we might also run into scenarios where an error fits into neither category and that'd be awkward.

Cutting down on boilerplate is always nice, of course.

I'll let you make the call on this.

**Comment by boastful-squirrel** [comment]
The argument about an error fitting into no/several categories is very true, didn't think about that. This will probably be the case with `IoError`, which can happen during compressing, and during uploading.

**Comment by boastful-squirrel** [comment]
I should be able to create a PR pretty soon

**Comment by boastful-squirrel** [comment]
Still working on it, that's a huge chunk. But well, no more panics when something goes wrong, that's worth it :)

**Comment by mglax** [comment]
Good, that's the only complain I have about miniserve.

**Comment by svenstaro** [comment]
Well, if that's your only problem you have with miniserve I'd say we did
pretty well. :D

**Comment by mglax** [comment]
Yeah it's an awesome tool!

**Comment by svenstaro** [comment]
Glad to hear you like it!

**Comment by boastful-squirrel** [comment]
I'm wondering if we couldn't simplify the errors to something like this

```
pub enum ContextualErrorKind {
    /// Any error with a fully custom message
    #[fail(display = "{}", _0)]
    CustomError(String),

    /// I/O errors
    #[fail(display = "{}. {}", _0, _1)]
    IOError(String, std::io::Error),

    /// Multipart errors
    #[fail(display = "Failed to process multipart request. {}", _0)]
    MultipartError(actix_web::error::MultipartError),
```

In the end, most our "custom errors" are unique, and I don't think having something like 
```
HTTPHeaderParseError,
UsernameTooLongError,
FooBarError,
BarBarError
```

Is easier to read than something like this
```
map_err(ContextualErrorKind::CustomError("Failed to parse HTTP header".to_string());
map_err(ContextualErrorKind::CustomError("Username length cannot exceed 255 characters".to_string()");
...
```

Maybe some errors can be grouped, I don't know... 

What do you think @svenstaro ?

**Comment by boastful-squirrel** [comment]
Edit: bad idea

**Comment by svenstaro** [comment]
Leaving this open until the very last `unwrap()` is gone :P

**Comment by boastful-squirrel** [comment]
On it
