### ISSUE TITLE
Search bar ?

### ISSUE THREAD

**Issue by boastful-squirrel** [svenstaro/miniserve#62]
What would you think about having a search bar to search for files in the listing ? I think that would be pretty useful for mobiles, when you can't easily CTRL+F. If that's an idea you like, I think we should make it compatible with both Javascript and no-Javascript users. 

I was thinking:

The search bar has a "Search" button. When clicking on it, the searched term is put as query parameter `?search=foobar`, then the server generates a page corresponding to that filtering. That would be compatible with no-javascript user. If Javascript is enabled, we simply hide the search button, and the filtering is performed in live using Javascript.

**Comment by svenstaro** [comment]
Not quite sure I like this. Especially the JS/non-JS part. Essentially that would have us implementing the same search (albeit not much code) server side and then in JS for optimum performance in both scenarios.

Also, in general, I'm not convinced we need a search. However, if you went ahead and whipped something up, I'd be happy to give it a spin and change my mind. I might not end up accepting that, though.

**Comment by boastful-squirrel** [comment]
No I didn't start, I was waiting for your input. I'll close this then
