### ISSUE TITLE
[Feature request] S3 support

### ISSUE THREAD

**Issue by pandruszkow** [svenstaro/miniserve#629]
Is there any interest in supporting S3 buckets as the data source? Something like https://play.minio.io:9443/buckets (username `minioadmin`, password `minioadmin`), but without the requirement to authenticate to access the data.

**Comment by svenstaro** [comment]
So you'd essentially make miniserve into an S3 proxy? Not sure, to be honest. There might be tools more suitable for that.

**Comment by Jikstra** [comment]
I don't think this would be useful for miniserve. It's about serving files from a fs, you could mount the s3 thingy somehow and serve that with miniserve, but why?

**Comment by Jikstra** [comment]
I propose to close this issue as it's out of scope in my opinion.

**Comment by svenstaro** [comment]
I agree, this seems out of scope.
