### ISSUE TITLE
`cargo install miniserve` compile error

### ISSUE THREAD

**Issue by bigdogs** [svenstaro/miniserve#693]
Updating crates.io index
  Installing miniserve v0.18.0
   Compiling libc v0.2.112
   Compiling version_check v0.9.4
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.36
   Compiling cfg-if v1.0.0
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.84
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling pin-project-lite v0.2.8
   Compiling futures-core v0.3.19
   Compiling bytes v1.1.0
   Compiling parking_lot_core v0.8.5
   Compiling typenum v1.15.0
   Compiling untrusted v0.7.1
   Compiling futures-sink v0.3.19
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.7.0
   Compiling once_cell v1.9.0
   Compiling futures-task v0.3.19
   Compiling futures-channel v0.3.19
   Compiling futures-util v0.3.19
   Compiling futures-io v0.3.19
   Compiling pin-utils v0.1.0
   Compiling slab v0.4.5
   Compiling serde_derive v1.0.133
   Compiling hashbrown v0.11.2
   Compiling crc32fast v1.3.0
   Compiling bitflags v1.3.2
   Compiling local-waker v0.1.2
   Compiling percent-encoding v2.1.0
   Compiling itoa v1.0.1
   Compiling serde v1.0.133
   Compiling ppv-lite86 v0.2.16
   Compiling tinyvec_macros v0.1.0
   Compiling adler v1.0.2
   Compiling paste v1.0.6
   Compiling lazy_static v1.4.0
   Compiling zstd-safe v4.1.2+zstd.1.5.1
   Compiling matches v0.1.9
   Compiling fnv v1.0.7
   Compiling itoa v0.4.8
   Compiling httparse v1.5.1
   Compiling regex-syntax v0.6.25
   Compiling encoding_rs v0.8.30
   Compiling siphasher v0.3.7
   Compiling convert_case v0.4.0
   Compiling proc-macro-hack v0.5.19
   Compiling ryu v1.0.9
   Compiling base64 v0.13.0
   Compiling serde_json v1.0.74
   Compiling mime v0.3.16
   Compiling time-macros v0.2.3
   Compiling unicode-bidi v0.3.7
   Compiling firestorm v0.5.0
   Compiling unicode-width v0.1.9
   Compiling pkg-config v0.3.24
   Compiling httpdate v1.0.2
   Compiling language-tags v0.3.2
   Compiling strsim v0.8.0
   Compiling ansi_term v0.12.1
   Compiling termcolor v1.1.2
   Compiling vec_map v0.8.2
   Compiling strsim v0.10.0
   Compiling beef v0.5.1
   Compiling codemap v0.1.3
   Compiling anyhow v1.0.52
   Compiling unchecked-index v0.2.2
   Compiling maud_htmlescape v0.17.1
   Compiling rle-decode-fast v1.0.1
   Compiling unicode-segmentation v1.8.0
   Compiling c_linked_list v1.1.1
   Compiling adler32 v1.2.0
   Compiling askama_escape v0.10.2
   Compiling http-range v0.1.4
   Compiling opaque-debug v0.3.0
   Compiling byteorder v1.4.3
   Compiling qrcodegen v1.7.0
   Compiling strum v0.22.0
   Compiling port_check v0.1.5
   Compiling alphanumeric-sort v1.4.3
   Compiling bytesize v1.1.0
   Compiling yansi v0.5.0
   Compiling hex v0.4.3
   Compiling instant v0.1.12
   Compiling generic-array v0.14.5
   Compiling unicase v2.6.0
   Compiling ahash v0.7.6
   Compiling cookie v0.16.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.7.0
   Compiling miniz_oxide v0.4.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-bigint v0.4.3
   Compiling num-rational v0.4.0
   Compiling lock_api v0.4.5
   Compiling bytestring v1.0.0
   Compiling actix-utils v3.0.0
   Compiling tinyvec v1.5.1
   Compiling tracing-core v0.1.21
   Compiling form_urlencoded v1.0.1
   Compiling http v0.2.6
   Compiling phf_shared v0.9.0
   Compiling textwrap v0.11.0
   Compiling libflate_lz77 v1.1.0
   Compiling time v0.3.5
   Compiling heck v0.3.3
   Compiling unicode-normalization v0.1.19
   Compiling tracing v0.1.29
   Compiling aho-corasick v0.7.18
   Compiling os_str_bytes v6.0.0
   Compiling twoway v0.2.2
   Compiling signal-hook-registry v1.4.0
   Compiling getrandom v0.2.3
   Compiling cpufeatures v0.2.1
   Compiling num_cpus v1.13.1
   Compiling socket2 v0.4.2
   Compiling time v0.1.43
   Compiling terminal_size v0.1.17
   Compiling atty v0.2.14
   Compiling xattr v0.2.2
   Compiling filetime v0.2.15
   Compiling get_if_addrs v0.5.3
   Compiling jobserver v0.1.24
   Compiling mio v0.7.14
   Compiling mio v0.8.0
   Compiling quote v1.0.14
   Compiling actix-service v2.0.2
   Compiling libflate v1.1.1
   Compiling idna v0.2.3
   Compiling mime_guess v2.0.3
   Compiling regex v1.5.4
   Compiling parking_lot v0.11.2
   Compiling rand_core v0.6.3
   Compiling textwrap v0.14.2
   Compiling tar v0.4.38
   Compiling cc v1.0.72
   Compiling clap v2.34.0
   Compiling flate2 v1.0.22
   Compiling tokio v1.15.0
   Compiling block-buffer v0.10.0
   Compiling crypto-common v0.1.1
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling url v2.2.2
   Compiling rand_chacha v0.3.1
   Compiling clap v3.0.4
   Compiling ring v0.16.20
   Compiling zstd-sys v1.6.2+zstd.1.5.1
   Compiling brotli-sys v0.3.2
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling chrono v0.4.19
   Compiling digest v0.10.1
   Compiling sha2 v0.9.8
   Compiling rand v0.8.4
   Compiling actix-router v0.5.0-beta.4
   Compiling lasso v0.5.1
   Compiling clap_complete v3.0.2
   Compiling tokio-util v0.6.9
   Compiling sha-1 v0.10.0
   Compiling simplelog v0.10.2
   Compiling chrono-humanize v0.2.1
   Compiling nanoid v0.4.0
   Compiling phf_generator v0.9.1
   Compiling clap_generate v3.0.1
   Compiling futures-macro v0.3.19
   Compiling actix-macros v0.2.3
   Compiling derive_more v0.99.17
   Compiling actix-web-codegen v0.5.0-rc.1
   Compiling thiserror-impl v1.0.30
   Compiling strum_macros v0.22.0
   Compiling actix-codec v0.4.2
   Compiling maud_macros v0.22.3
   Compiling phf_macros v0.9.0
   Compiling actix-rt v2.5.1
   Compiling thiserror v1.0.30
   Compiling maud v0.22.3
   Compiling phf v0.9.0
   Compiling grass v0.10.8
   Compiling bzip2 v0.4.3
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling webpki v0.21.4
   Compiling sct v0.6.1
   Compiling zip v0.5.13
   Compiling webpki-roots v0.22.2
   Compiling h2 v0.3.9
   Compiling local-channel v0.1.2
   Compiling actix-server v2.0.0-rc.3
   Compiling futures-executor v0.3.19
   Compiling rustls v0.20.2
   Compiling rustls v0.19.1
   Compiling futures v0.3.19
   Compiling serde_urlencoded v0.7.0
   Compiling tokio-rustls v0.23.2
   Compiling actix-tls v3.0.0
   Compiling brotli2 v0.3.2
   Compiling miniserve v0.18.0
   Compiling zstd v0.9.1+zstd.1.5.1
   Compiling actix-http v3.0.0-beta.18
   Compiling actix-web v4.0.0-beta.19
   Compiling actix-files v0.6.0-beta.13
   Compiling actix-web-httpauth v0.6.0-beta.7
   Compiling actix-multipart v0.4.0-beta.12
error[E0432]: unresolved import `clap::crate_version`
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:14:12
   |
14 | use clap::{crate_version, IntoApp, Parser};
   |            ^^^^^^^^^^^^^ no `crate_version` in the root

error[E0432]: unresolved import `actix_web::http::ContentEncoding`
 --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/archive.rs:1:5
  |
1 | use actix_web::http::ContentEncoding;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ContentEncoding` in `http`

error[E0432]: unresolved import `actix_web::body::AnyBody`
 --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/errors.rs:3:5
  |
3 |     body::AnyBody,
  |     ^^^^^^^^^^^^^ no `AnyBody` in `body`

error[E0432]: unresolved import `actix_web::body::Body`
 --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/listing.rs:1:5
  |
1 | use actix_web::body::Body;
  |     ^^^^^^^^^^^^^^^^^^^^^ no `Body` in `body`

error[E0432]: unresolved import `actix_web::dev::BodyEncoding`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/listing.rs:160:9
    |
160 |     use actix_web::dev::BodyEncoding;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `BodyEncoding` in `dev`

error[E0432]: unresolved imports `clap::crate_name`, `clap::crate_version`
 --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/renderer.rs:4:12
  |
4 | use clap::{crate_name, crate_version};
  |            ^^^^^^^^^^  ^^^^^^^^^^^^^ no `crate_version` in the root
  |            |
  |            no `crate_name` in the root

error: cannot determine resolution for the macro `crate_version`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:107:19
    |
107 |         version = crate_version!()
    |                   ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/renderer.rs:195:45
    |
195 |            (format!("{}/{}", crate_name!(), crate_version!()))
    |                                             ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/renderer.rs:195:30
    |
195 |            (format!("{}/{}", crate_name!(), crate_version!()))
    |                              ^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: cannot find derive macro `Parser` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:11:10
   |
11 | #[derive(Parser)]
   |          ^^^^^^
   |
note: `Parser` is imported here, but it is only a trait, without a derive macro
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:1:12
   |
1  | use clap::{Parser, ValueHint};
   |            ^^^^^^

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:12:3
   |
12 | #[clap(name = "miniserve", author, about, version)]
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:15:7
   |
15 |     #[clap(short = 'v', long = "verbose")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:19:7
   |
19 |     #[clap(name = "PATH", parse(from_os_str), value_hint = ValueHint::AnyPath)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:26:7
   |
26 |     #[clap(long, parse(from_os_str), name = "index_file", value_hint = ValueHint::FilePath)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:34:7
   |
34 |     #[clap(long, requires = "index_file")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:38:7
   |
38 |     #[clap(short = 'p', long = "port", default_value = "8080")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:42:7
   |
42 |     #[clap(
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:54:7
   |
54 |     #[clap(
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:64:7
   |
64 |     #[clap(long = "random-route")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:68:7
   |
68 |     #[clap(short = 'P', long = "no-symlinks")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:72:7
   |
72 |     #[clap(short = 'H', long = "hidden")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:76:7
   |
76 |     #[clap(
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:86:7
   |
86 |     #[clap(
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:96:7
   |
96 |     #[clap(short = 'q', long = "qrcode")]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:100:7
    |
100 |     #[clap(short = 'u', long = "upload-files")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:104:7
    |
104 |     #[clap(short = 'o', long = "overwrite-files")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:108:7
    |
108 |     #[clap(short = 'r', long = "enable-tar")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:112:7
    |
112 |     #[clap(short = 'g', long = "enable-tar-gz")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:119:7
    |
119 |     #[clap(short = 'z', long = "enable-zip")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:123:7
    |
123 |     #[clap(short = 'D', long = "dirs-first")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:127:7
    |
127 |     #[clap(short = 't', long = "title")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:131:7
    |
131 |     #[clap(
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:140:7
    |
140 |     #[clap(short = 'l', long = "show-symlink-info")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:144:7
    |
144 |     #[clap(short = 'F', long = "hide-version-footer")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:148:7
    |
148 |     #[clap(short = 'W', long = "show-wget-footer")]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:152:7
    |
152 |     #[clap(long = "print-completions", value_name = "shell", arg_enum)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:157:7
    |
157 |     #[clap(long = "tls-cert", requires = "tls-key", value_hint = ValueHint::FilePath)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:162:7
    |
162 |     #[clap(long = "tls-key", requires = "tls-cert", value_hint = ValueHint::FilePath)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error[E0277]: the trait bound `BoxBody: std::convert::From<&str>` is not satisfied
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:360:28
    |
360 |         .message_body(logo.into())
    |                            ^^^^ the trait `std::convert::From<&str>` is not implemented for `BoxBody`
    |
    = note: required because of the requirements on the impl of `Into<BoxBody>` for `&str`

error[E0277]: the trait bound `BoxBody: std::convert::From<&str>` is not satisfied
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:367:27
    |
367 |         .message_body(css.into())
    |                           ^^^^ the trait `std::convert::From<&str>` is not implemented for `BoxBody`
    |
    = note: required because of the requirements on the impl of `Into<BoxBody>` for `&str`

error[E0599]: the method `and_then` exists for reference `&ContentDisposition`, but its trait bounds were not satisfied
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/file_upload.rs:48:10
    |
48  |         .and_then(|cd| cd.get_filename().map(String::from))
    |          ^^^^^^^^ method cannot be called on `&ContentDisposition` due to unsatisfied trait bounds
    |
   ::: /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/http/header/content_disposition.rs:305:1
    |
305 | pub struct ContentDisposition {
    | -----------------------------
    | |
    | doesn't satisfy `ContentDisposition: TryStreamExt`
    | doesn't satisfy `ContentDisposition: TryStream`
    |
    = note: the following trait bounds were not satisfied:
            `&ContentDisposition: TryStream`
            which is required by `&ContentDisposition: TryStreamExt`
            `&&ContentDisposition: TryStream`
            which is required by `&&ContentDisposition: TryStreamExt`
            `&mut &ContentDisposition: TryStream`
            which is required by `&mut &ContentDisposition: TryStreamExt`
            `ContentDisposition: TryStream`
            which is required by `ContentDisposition: TryStreamExt`
            `&mut ContentDisposition: TryStream`
            which is required by `&mut ContentDisposition: TryStreamExt`

error[E0599]: no method named `extensions` found for reference `&HttpRequest` in the current scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/listing.rs:157:26
    |
157 |     let extensions = req.extensions();
    |                          ^^^^^^^^^^ method not found in `&HttpRequest`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use actix_web::HttpMessage;
    |

error[E0599]: no method named `encoding` found for mutable reference `&mut HttpResponseBuilder` in the current scope
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/listing.rs:361:18
    |
361 |                 .encoding(archive_method.content_encoding())
    |                  ^^^^^^^^ method not found in `&mut HttpResponseBuilder`

error[E0599]: no function or associated item named `parse` found for struct `CliArgs` in the current scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:34:31
   |
34 |     let args = args::CliArgs::parse();
   |                               ^^^^^ function or associated item not found in `CliArgs`
   |
  ::: /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:13:1
   |
13 | pub struct CliArgs {
   | ------------------ function or associated item `parse` not found for this
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following traits define an item `parse`, perhaps you need to implement one of them:
           candidate #1: `actix_web::http::header::Header`
           candidate #2: `parsing::parsable::sealed::Sealed`
           candidate #3: `actix_web_httpauth::headers::authorization::Scheme`
           candidate #4: `Parser`

error[E0599]: no function or associated item named `into_app` found for struct `CliArgs` in the current scope
  --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:37:43
   |
37 |         let mut clap_app = args::CliArgs::into_app();
   |                                           ^^^^^^^^ function or associated item not found in `CliArgs`
   |
  ::: /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/args.rs:13:1
   |
13 | pub struct CliArgs {
   | ------------------ function or associated item `into_app` not found for this
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `into_app`, perhaps you need to implement it:
           candidate #1: `IntoApp`

error[E0271]: type mismatch resolving `<HttpAuthentication<BasicAuth, fn(ServiceRequest, BasicAuth) -> impl futures::Future<Output = Result<ServiceRequest, actix_web::Error>> {handle_auth}> as Transform<actix_web::scope::ScopeService, ServiceRequest>>::Response == ServiceResponse`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:199:27
    |
199 |                       .wrap(middleware::Condition::new(
    |  ______________________----_^
    | |                      |
    | |                      required by a bound introduced by this call
200 | |                         !inside_config.auth.is_empty(),
201 | |                         HttpAuthentication::basic(auth::handle_auth),
202 | |                     ))
    | |_____________________^ expected struct `BoxBody`, found enum `EitherBody`
    |
    = note: expected struct `ServiceResponse<BoxBody>`
               found struct `ServiceResponse<EitherBody<_>>`
    = note: required because of the requirements on the impl of `Transform<actix_web::scope::ScopeService, ServiceRequest>` for `Condition<HttpAuthentication<BasicAuth, fn(ServiceRequest, BasicAuth) -> impl futures::Future<Output = Result<ServiceRequest, actix_web::Error>> {handle_auth}>>`
note: required by a bound in `Scope::<T, B>::wrap`
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/scope.rs:318:12
    |
318 |           M: Transform<
    |  ____________^
319 | |             T::Service,
320 | |             ServiceRequest,
321 | |             Response = ServiceResponse<B1>,
322 | |             Error = Error,
323 | |             InitError = (),
324 | |         >,
    | |_________^ required by this bound in `Scope::<T, B>::wrap`

error[E0308]: mismatched types
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:215:61
    |
215 |             Some(tls_config) => srv.listen_rustls(listener, tls_config.clone()),
    |                                                             ^^^^^^^^^^^^^^^^^^ expected struct `rustls::server::server_conn::ServerConfig`, found struct `ServerConfig`
    |
note: return type inferred to be `rustls::server::server_conn::ServerConfig` here
   --> /Users/aaa/.cargo/registry/src/github.com-1ecc6299db9ec823/miniserve-0.18.0/src/main.rs:209:24
    |
209 |           let listener = create_tcp_listener(*addr).map_err(|e| {
    |  ________________________^
210 | |             ContextualError::IoError(format!("Failed to bind server to {}", addr), e)
211 | |         })?;
    | |___________^

Some errors have detailed explanations: E0271, E0277, E0308, E0432, E0599.
For more information about an error, try `rustc --explain E0271`.
error: failed to compile `miniserve v0.18.0`, intermediate artifacts can be found at `/var/folders/3l/wpxv999d4wxgycsmrmqjf_t00000gn/T/cargo-installQ1ZZ4r`

Caused by:
  could not compile `miniserve` due to 47 previous errors

**Comment by svenstaro** [comment]
The log is really hard to read, please upload it as a text file rather. Did you try `cargo install --locked miniserve`?

**Comment by albel727** [comment]
I've had the same error while updating with `cargo install` and `cargo install-update` and it's easily reproducible this way. An API breakage in the beta versions of `actix-web` and `clap`, that miniserve depends on, is the obvious culprit. The `cargo install --locked miniserve` workaround works.
