### ISSUE TITLE
Implement RFSAPI support

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/miniserve#7]
Look into RFSAPI support.

- https://github.com/nabijaczleweli/rfsapi-rs
- https://github.com/thecoshman/doh

**Comment by Jikstra** [comment]
I think aiming for webdav is the better approach here, as it's standardized and there's dav2fs (among others) which allows mounting a webdav. Including uploading/downloading/mkdir/move...

**Comment by svenstaro** [comment]
Closing in favor of #293.
