### ISSUE TITLE
Add support for media streaming (video files)

### ISSUE THREAD

**Issue by ClementNerma** [svenstaro/miniserve#732]
Hi there!

I've been using Miniserve for a quite a bit now, and I'm really enjoying this tool. But I find it misses a feature I'd personally would love to see: video streaming.

If I go the URI of a picture for instance it will be displayed by the browser correctly. But if it's an  ~~video~~ audio file (e.g. MP~~4~~3) it will be downloaded instead of being played.

Would it be possible to implement support for these formats? I have no idea if it would be complicated, just thought I'd throw the idea here :)

**Comment by svenstaro** [comment]
This should be really easy actually and should only be a matter of sending the browser the right MIME type in the header.

**Comment by ClementNerma** [comment]
If it's that simple I'll dig into the code and try to make a PR for that :)

**Comment by ClementNerma** [comment]
From what I understand, you're using `actix-files` for serving and `miniserve` doesn't in fact handle MIME types itself, it is delegated.

```
if !conf.path.is_file() {
    if conf.file_upload {
        // Allow file upload
        app.service(web::resource("/upload").route(web::post().to(file_upload::upload_file)));
    }
    // Handle directories
    app.service(files_service());
} else {
    // Handle single files
    app.service(web::resource(["", "/"]).route(web::to(listing::file_handler)));
}
```

```
pub async fn file_handler(req: HttpRequest) -> actix_web::Result<actix_files::NamedFile> {
    let path = &req.app_data::<crate::MiniserveConfig>().unwrap().path;
    actix_files::NamedFile::open(path).map_err(Into::into)
}
```

Which makes me unsure if this can be dealt with inside miniserve directly?

**Comment by aliemjay** [comment]
Can you confirm that you check the `Content-Disposition` and `Content-Type` headers you recieve, because the default settings should handle video files correctly. See:
https://github.com/actix/actix-web/blob/1d1a65282f9d9ad122fec27627e53a86f7d33304/actix-files/src/named.rs#L130

Anyway we can override the default with `actix_files::Files::mime_override`.

**Comment by ClementNerma** [comment]
Oh sorry I miscorrected my issue earlier, I was talking about audio files (MP3 specifically). Videos indeed work.

**Comment by svenstaro** [comment]
What headers do you get returned for your MP3s?

**Comment by ClementNerma** [comment]
> What headers do you get returned for your MP3s?

I get `audio/mpeg`, but inspecting the other headers I see it is also sent as an attachment. Here is the full headers list:

```
HTTP/1.1 200 OK
content-length: 6005429
last-modified: Mon, 15 Feb 2021 14:44:16 GMT
etag: "100000000fc14:5d512d:602a88c0:10acfa34"
content-type: audio/mpeg
accept-ranges: bytes
content-disposition: attachment; filename="XXXXX.mp3"
date: Wed, 09 Feb 2022 22:18:33 GMT
```

**Comment by svenstaro** [comment]
Weird, where does `content-disposition: attachment` come from when it doesn't appear for videos?

**Comment by ClementNerma** [comment]
> Weird, where does `content-disposition: attachment` come from when it doesn't appear for videos?

I suppose it comes from the `actix-files` crate as it is the one responsible for treating such files? Videos get a `content-disposition: inline` instead, but if I look at the [link provided by @aliemjay](https://github.com/actix/actix-web/blob/1d1a65282f9d9ad122fec27627e53a86f7d33304/actix-files/src/named.rs#L130) we can see that there is no audio files support in the crate, only image, text, video and JS/JSON/WASM. Otherwise, it sends an attachment header.

I'll open an issue in that repository to see if the problem indeed comes from their side.

**Comment by svenstaro** [comment]
Ah yes, good catch!

**Comment by mzakharo** [comment]
it looks like https://github.com/actix/actix-web/issues/2644 has been resolved, any update on audio streaming in miniserve? Audio (.wav) streaming still does not work for me on miniserve 0.19.5

**Comment by ClementNerma** [comment]
It's because there hasn't been a new release for `actix-files` since 3 months, and I don't know when the next one will happen :/

**Comment by svenstaro** [comment]
Could you test the current master? https://github.com/actix/actix-web/pull/2645 is closed and it's released.

**Comment by svenstaro** [comment]
Actually I see now that miniserve 0.20.0 should actually already have this. Please check and report back! :)

**Comment by rayanmargham** [comment]
What's going on I'm so confused, can't you already stream video with actix?

**Comment by ClementNerma** [comment]
> What's going on I'm so confused, can't you already stream video with actix?

Absolutely, it's just that actix-files was not reporting the correct MIME type which made the browser download it instead of streaming it.

**Comment by svenstaro** [comment]
So does this now work for you guys as expected?
