### ISSUE TITLE
Files beginning with a dot (e.g. .treeinfo) return a 400 request

### ISSUE THREAD

**Issue by yar999** [svenstaro/miniserve#749]
Files beginning with a dot (e.g. .treeinfo) return a 400 request

```sh
> curl localhost:8080/.treeinfo
<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" type="image/svg+xml" href="/d8f6a5dc32"><link rel="stylesheet" href="/1193418e31"><title>400 Bad Request</title></head><body class="default_theme_squirrel default_theme_dark_archlinux">
                    <script>
                        // read theme from local storage and apply it to body
                        var theme = localStorage.getItem('theme');
                        if (theme != null && theme != 'default') {
                            document.body.classList.add('theme_' + theme);
                        }
                    </script>
                    <div class="error"><p>400 Bad Request</p><p>The segment started with the wrapped invalid character</p><div class="error-nav"><a class="error-back" href="/">Go back to file listing</a></div><p class="footer"><div class="version">miniserve/0.19.2</div></p></div></body></html>
```

**Comment by svenstaro** [comment]
Just to confirm: Did you pass `--hidden`?

**Comment by equal-l2** [comment]
This error comes from [`actix-files`](https://github.com/actix/actix-web/blob/1bd2076b35f9c9bcc6ef9fe96f157c4de0cbd7cc/actix-files/src/service.rs#L123-L129) and seems unable to override currently.

**Comment by svenstaro** [comment]
Oh, good find. That's certainly worth bringing up upstream I think.

**Comment by equal-l2** [comment]
More specifically, the path parser in actix-files returns an error for file names beginning with a dot, unless the option for hidden files is enabled.
https://github.com/actix/actix-web/blob/1bd2076b35f9c9bcc6ef9fe96f157c4de0cbd7cc/actix-files/src/path_buf.rs#L47-L48

**Comment by equal-l2** [comment]
Anyway, I believe adding `--hidden` option solves the real problem for miniserve users because dot-prefixed files are not shown without the option, making users unable to those files.

**Comment by aliemjay** [comment]
> dot-prefixed files are not shown without the option, making users unable to those files.

I believe this is the intended behavior for `--hidden`. dot-prefixed paths are considered hidden by convention even in Windows.

**Comment by equal-l2** [comment]
Yeah, I mean it.
Unless `--hidden` is applied, dot-prefixed files are hidden from the file list and users won't access them, so I think 400 errors for those files (when without `--hidden`) are not a real problem.

**Comment by equal-l2** [comment]
It would be beneficial if the upstream has a customization point for the error, though.

**Comment by yar999** [comment]
`--hidden`  is ok, thank you @svenstaro
