### ISSUE TITLE
Proposal: Password Hashing

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#75]
## Problem

miniserve already has an `--auth` feature, the problem is, the password is publicly visible. This makes it impossible to expose the command line to the public.

## Solution

Support `--auth username:sha256:password_hash` syntax in addition to the old syntax.

---

P.S. I am trying to learn Rust by contributing to this repository, so don't implement this feature just yet.

**Comment by svenstaro** [comment]
Alternatively, the normal auth option could be extended to accept a hash
prefix such as sha256 and then we don't have to add a parameter per
password hash type.

**Comment by svenstaro** [comment]
To clarify, it would look like this: --auth hi:sha256:hash

Think about it.

**Comment by KSXGitHub** [comment]
> --auth hi:sha256:hash

It looks cool.

**Comment by KSXGitHub** [comment]
@svenstaro I find using `:` as separator to be pretty limited. What if we want to support other things (e.g. salt) in the future?

How about this?

```
--auth username%sha256#hash&salt
```

The idea is: Instead of using `:` as separator, I want to use `:`, `%`, `#`, `&` as leading indicators.

**Comment by svenstaro** [comment]
I don't want to overcomplicate this too much. After all, this tool's
primary selling point is ease of use. I don't think we need a salt.

**Comment by svenstaro** [comment]
That said' I'd be ok with using another separator.

**Comment by KSXGitHub** [comment]
Well, I already edit `parse_base_auth` and I don't want to change it again because I'm lazy.
