### ISSUE TITLE
Create directory feature

### ISSUE THREAD

**Issue by sheepy0125** [svenstaro/miniserve#768]
Hello there!

I've been using Miniserve as a sort of "non-deletable" backup system, and I love it!
However, I'd love for there to be a way to create a directory, and it seems a couple other people would too (#502 and #510).
In #502, [david0u0](https://github.com/david0u0) also addressed this and submitted a pull request (#512). However, they disappeared after a change was requested.

I was wondering if I could try doing this and if such a change would be accepted.

My idea is to have another box similar to the "upload files" one, where one could enter a name for the directory to create. I would also like to enter something like `hello/there` to create a directory `there` inside of another directory `hello`. Lastly, I would like to have an `--enable-mkdir` flag. 

Thanks!

**Comment by svenstaro** [comment]
Concept sounds fine to me, feel free to go ahead as planned. :)
