### ISSUE TITLE
Hide your API key

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#77]
Are you sure you want to leave [this key](https://github.com/svenstaro/miniserve/blob/1ae2c99806d3f8fad84202fc3c6346f42247ea26/.travis.yml#L66) visible to the public?

**Comment by svenstaro** [comment]
Yes. It is a protected asymmetrically encrypted travis API key. What more do you think I should do to protect it?

**Comment by KSXGitHub** [comment]
Then it is secured I suppose.

**Comment by KSXGitHub** [comment]
Actually, although it is secured,it is still inconvenient for other forks to deploy their own miniserve. I want to make some changes to `.travis.yml` and test it (deploy) on my own fork.

Can you change it to a secret environment variable?
