### ISSUE TITLE
`--index` if index.html exists?

### ISSUE THREAD

**Issue by DUOLabs333** [svenstaro/miniserve#784]
It would be nice if by default, if index.html is found, `miniserve` does `--index index.html`.

**Comment by svenstaro** [comment]
Hm not sure, this might be surprising behavior for users who are used to miniserve just serving the current dir as is. If you did that and had `--upload` active, someone could upload an `index.html` and then miniserve would stop serving the dir index. I'm not sure I like that behavior.

**Comment by svenstaro** [comment]
We have something like this now with --readme. Does that work for you?

**Comment by DUOLabs333** [comment]
Not really, but I don't really need this feature anymore --- I just made a wrapper script that hardcodes `--index`.
