### ISSUE TITLE
Route prefix support for css

### ISSUE THREAD

**Issue by solarknight** [svenstaro/miniserve#804]
I use miniserve as a kubernetes service behind a gateway like nginx. If set --route-prefix with miniserve, the request can be correctly passed to miniserve, but the subsequent css request is 404. Add route prefix support for the css & favicon can solve this.
e.g. miniserve set with --route-prefix myfile
nginx proxy pass ${domain}/myfile request to miniserve
subsequent css request is like ${domain}/<random_route> and cause 404

**Comment by svenstaro** [comment]
Hm that's a bug but it should be easy to fix. We had problems with this in the past. Would you like to take a stab at this?

**Comment by svenstaro** [comment]
@solarknight friendly ping :)
