### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by HongxuChen** [svenstaro/miniserve#807]
I installed the miniserve on Linux with `cargo install --locked miniserve` and in my home directory I executed ` miniserve $PWD -p 8089`. It reported the following messages:

```bash
miniserve v0.19.5
10:09:35 [ERROR] Failed to bind server to [::]:8089
10:09:35 [ERROR] caused by: Address family not supported by protocol (os error 97)
Error: Failed to bind server to [::]:8089
caused by: Address family not supported by protocol (os error 97)
```

What may be the causes and what should I do to make it work properly?

BTW, I'm using behind a proxy.

**Comment by svenstaro** [comment]
Try binding to a specific interface like `miniserve -i 0.0.0.0`.

**Comment by HongxuChen** [comment]
It works, thanks!
