### ISSUE TITLE
 Unusable path

### ISSUE THREAD

**Issue by zy1818** [svenstaro/miniserve#811]
miniserve.exe -p 12345 -- E:\ONEDRIVE\5T\OneDrive - automation\H\

thank you

**Comment by zy1818** [comment]
If there is "-" in the path, the program cannot run





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svenstaro/miniserve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [svenstaro/miniserve]  Unusable path (Issue #811)





 
Sorry I don't have Windows - what's the error and what's supposed to happen?

**Comment by svenstaro** [comment]
Can you try quoting like `miniserve.exe -p 12345 -- "E:\ONEDRIVE\5T\OneDrive - automation\H\"`?

**Comment by svenstaro** [comment]
Please check here whether any of the techniques work for you: https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/

**Comment by zy1818** [comment]
谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svenstaro/miniserve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [svenstaro/miniserve]  Unusable path (Issue #811)





 
Please check here whether any of the techniques work for you: https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/

**Comment by zy1818** [comment]
miniserve.exe -p 9999 -- "E:\ONEDRIVE\5T\OneDrive - automation\plc\松下a5接线.xlsx"
&nbsp;
this&nbsp;ok


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svenstaro/miniserve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [svenstaro/miniserve]  Unusable path (Issue #811)





 
Please check here whether any of the techniques work for you: https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/

**Comment by zy1818** [comment]
miniserve.exe -p 9999 -- "E:\ONEDRIVE\5T\OneDrive - automation\plc"&nbsp;


this&nbsp;ok






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svenstaro/miniserve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [svenstaro/miniserve]  Unusable path (Issue #811)





 
Please check here whether any of the techniques work for you: https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/

**Comment by svenstaro** [comment]
Cool!
