### ISSUE TITLE
Configuration with Environment variables

### ISSUE THREAD

**Issue by genofire** [svenstaro/miniserve#829]
It would be really nice, to configurate miniserve with env variables.

(In k8s it is possible to store Password safe in "Secrets" and use them as envFrom with secretRef - so basic auth credentials could be stored secure.)

**Comment by svenstaro** [comment]
Yeah, we should be able to get this functionality with very little effort thanks to clap as it's built-in. Want to take a stab at it?

**Comment by svenstaro** [comment]
Yeah should be pretty simple. Would you like to make a PR? I'm not sure when I'd get to it.

**Comment by onedr0p** [comment]
I am not familiar with Rust, nor use miniserve... only a has-been developer here 😆  I was just looking around for alternative options to [filebrowser](https://github.com/filebrowser/filebrowser) which I am currently using.

**Comment by svenstaro** [comment]
Can you guys check whether https://github.com/svenstaro/miniserve/pull/1160 works for you?

**Comment by onedr0p** [comment]
Looks good to me, thanks! @svenstaro
