### ISSUE TITLE
set upload folder

### ISSUE THREAD

**Issue by UltraBlackLinux** [svenstaro/miniserve#842]
Hey there,
I would love to have a feature that allowed me to use the -u flag with a folder, so only that folder can be uploaded to.
Can you add this?
Thanks!

**Comment by svenstaro** [comment]
So something like `--restrict-upload-dir` and then trying to upload into any other directory would give an error? Sounds like a neat little feature. Would you like to take a stab at this?

**Comment by UltraBlackLinux** [comment]
> So something like `--restrict-upload-dir` and then trying to upload into any other directory would give an error? Sounds like a neat little feature. Would you like to take a stab at this?

Maybe not even an error (At least not in the web UI). More that the Upload Button only appears in the predifined directory(s) (A list would definitely be useful)

Sadly I am 100% unfamiliar with rust, and this does probably require more knowledge than just copy-pasting stuff around. Someone else will have to do this.

**Comment by jonasdiemer** [comment]
Hi,

looking for an opportunity for some first Rust experience, I've taken a stab: https://github.com/jonasdiemer/miniserve/tree/restrict-upload-dir

Please consider it a rough prototype - esp. the area in [file_upload.rs](https://github.com/jonasdiemer/miniserve/blob/9e358d7d2534197e5b6170626d5b8f2add76705f/src/file_upload.rs#L176) doesn't feel very idiomatic... 

@svenstaro, I'd be happy if you could take a look and suggest what to add/change/improve. Thanks!

**Comment by svenstaro** [comment]
Make a draft PR and I'll take a look.
