### ISSUE TITLE
How to write systemd service file for non-root users?

### ISSUE THREAD

**Issue by orwithout** [svenstaro/miniserve#871]
The username used is : "jks"  ,The experiment failed:

mkdir -p  /home/jks/.config/systemd/user/
vim  /home/jks/.config/systemd/user/miniserve@.service
Written（https://raw.githubusercontent.com/svenstaro/miniserve/master/packaging/miniserve%40.service）:

[Unit]
Description=miniserve for %i
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
ExecStart=/usr/bin/miniserve -- %I
IPAccounting=yes
IPAddressAllow=localhost
IPAddressDeny=any
DynamicUser=yes
PrivateTmp=yes
PrivateUsers=yes
PrivateDevices=yes
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_DAC_READ_SEARCH

[Install]
WantedBy=multi-user.target

cd /home/jks
curl -LO https://github.com/svenstaro/miniserve/releases/download/v0.20.0/miniserve-v0.20.0-x86_64-unknown-linux-musl
sudo cp  /home/jks/miniserve-v0.20.0-x86_64-unknown-linux-musl  /usr/bin/miniserve
sudo chmod +x  /usr/bin/miniserve

sudo usermod -a -G systemd-journal jks    #Permission to view systemd logs

systemctl --user daemon-reload
systemctl --user start miniserve@-home-jks
systemctl --user status miniserve@-home-jks
![image](https://user-images.githubusercontent.com/19142891/184302667-1ca31ef1-fcff-412d-9d7b-da1cd1d31fa3.png)

journalctl -e
![image](https://user-images.githubusercontent.com/19142891/184302971-e4020318-e24e-4449-91b9-dfed61519192.png)

**Comment by svenstaro** [comment]
If you want to use a fixed user, you can't use 
```
DynamicUser=yes
```
There might be other security parameters which you'll have to disable to for user services but the log should generally tell you.
