### ISSUE TITLE
Will it support SMB server with auth?

### ISSUE THREAD

**Issue by chaooe** [svenstaro/miniserve#874]
Thanks for implement this prefect tools. It helped a lot , we can use this tool and intergate into our system easily.
Currently we faced an problems is we need to use SMB server to store our logs and traces and videos. So is it possible to add this feature?

**Comment by jonasdiemer** [comment]
I don't think that adding a whole different protocol (SMB vs HTTP) would make sense - that should rather be a separate piece of software (see https://www.samba.org).

**Comment by svenstaro** [comment]
Yes, I also think this is quite likely out of scope.

**Comment by chaooe** [comment]
Okay. but also i got another solution which can support SMB.  
1. For windows:
we can "Map Network drive" to a SMB server as a new Drive, e.g: H:
so we can use miniserve to the drive

for other platform, i haven't test it. but i think it should be similar.

**Comment by chaooe** [comment]
Got solution for smb
