### ISSUE TITLE
The `wget` command from `--show-wget-footer` with `--random-route` doesn't include the random route.

### ISSUE THREAD

**Issue by alexschrod** [svenstaro/miniserve#876]
Version: 0.20.0

As an example, when I browse http://172.24.144.1:8080/13bfe2/ the wget footer says
> Download folder: `wget -r -c -nH -np --cut-dirs=0 -R "index.html*" "http://172.24.144.1:8080/?raw=true"`

which, naturally, produces leads to a 404 error if you try to use it.

**Comment by svenstaro** [comment]
This should now be fixed as of 0.23.0. If it doesn't for you for some reason, please request to reopen.
