### ISSUE TITLE
[Feature Request] UPnP port forward

### ISSUE THREAD

**Issue by escape0707** [svenstaro/miniserve#897]
Is there any possibility to add UPnP port forwarding support, so I can share files to my friends living somewhere else even easier?

**Comment by jonasdiemer** [comment]
Hi there,

have you looked into stand-alone options like https://github.com/FloGa/upnp-daemon ? Not sure it would make sense to duplicate that functionality in miniserve (ease of use may be a reason).

Regards
Jonas

**Comment by escape0707** [comment]
Thank you. I will try that. Previously I was using upnpc manually with miniserve.
