### ISSUE TITLE
Heads-up: miniserve is about to be included in the FreeBSD ports collection 

### ISSUE THREAD

**Issue by 0mp** [svenstaro/miniserve#9]
Ticket: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228324

Everything works perfectly fine 👍 

I'll ping you once it is in the ports. 

Cheers & happy hacking!

**Comment by svenstaro** [comment]
Cheers!

**Comment by svenstaro** [comment]
Well, what's the status here?

**Comment by 0mp** [comment]
@svenstaro There were some issues with dependencies. I am going get back to this issue soon.

**Comment by 0mp** [comment]
Let's close it for now. I'll create a PR if miniserve makes it to the FreeBSD ports. Cheers!

**Comment by 0mp** [comment]
The time has come: https://www.freshports.org/www/miniserve

Cheers!

**Comment by svenstaro** [comment]
Thanks a ton!
