### ISSUE TITLE
0.22.0: Windows artifacts missing

### ISSUE THREAD

**Issue by AntonOks** [svenstaro/miniserve#913]
no **_miniserve-v0.22.0-x86_64-pc-windows-msvc.exe_** files were released?!

**Comment by svenstaro** [comment]
https://github.com/svenstaro/miniserve/releases/download/v0.22.0/miniserve-0.22.0-x86_64-pc-windows-msvc.exe it's right here. Did you click 
![image](https://user-images.githubusercontent.com/1664/191818889-1263a31c-fc84-4312-a984-eecf54386b63.png)
?

**Comment by AntonOks** [comment]
sorry, my bad.

Had a "problem" with my SCOOP pckg mgr. Didn't find the new artifact due to the change in the "file name"... and I haven't seen one on the first glance, so...


```
before: https://github.com/svenstaro/miniserve/releases/download/v0.22.0/miniserve-0.22.0-x86_64-pc-windows-msvc.exe
now:    https://github.com/svenstaro/miniserve/releases/download/v0.20.0/miniserve-**_v_**0.20.0-x86_64-pc-windows-msvc.exe
```

THANKS!
