### ISSUE TITLE
Use clippy to improve code quality

### ISSUE THREAD

**Issue by KSXGitHub** [svenstaro/miniserve#93]
[Clippy](https://github.com/rust-lang/rust-clippy) is a linter for Rust. It prevents us from making common mistakes. I've recently tried running `cargo clippy` for `main.rs` and this is what I got:

<details>
<summary>Clippy warnings</summary>

<pre><font color="#89E234"><b>    Checking</b></font> miniserve v0.4.1 (/home/khai/programming/miniserve)
<font color="#FBE84F"><b>warning</b></font><b>: writing `&amp;Vec&lt;_&gt;` instead of `&amp;[_]` involves one more reference and cannot be used with non-Vec-based slices.</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/auth.rs:78:56
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>78</b></font> <font color="#729ECF"><b>| </b></font>pub fn compare_hash&lt;T: Digest&gt;(password: String, hash: &amp;Vec&lt;u8&gt;) -&gt; bool {
   <font color="#729ECF"><b>| </b></font>                                                       <font color="#FBE84F"><b>^^^^^^^^</b></font> <font color="#FBE84F"><b>help: change this to: `&amp;[u8]`</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::ptr_arg)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

<font color="#FBE84F"><b>warning</b></font><b>: identical conversion</b>
   <font color="#729ECF"><b>--&gt; </b></font>src/listing.rs:159:18
    <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>159</b></font> <font color="#729ECF"><b>| </b></font>    for entry in dir.path.read_dir()? {
    <font color="#729ECF"><b>| </b></font>                 <font color="#FBE84F"><b>^^^^^^^^^^^^^^^^^^^^</b></font> <font color="#FBE84F"><b>help: consider removing `dir.path.read_dir()?()`: `dir.path.read_dir()?`</b></font>
    <font color="#729ECF"><b>|</b></font>
    <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::identity_conversion)] on by default
    <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion

<font color="#FBE84F"><b>warning</b></font><b>: this function has too many arguments (11/7)</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/renderer.rs:12:1
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>12</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>/</b></font> pub fn page(
<font color="#729ECF"><b>13</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     serve_path: &amp;str,
<font color="#729ECF"><b>14</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     entries: Vec&lt;Entry&gt;,
<font color="#729ECF"><b>15</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     is_root: bool,
<font color="#729ECF"><b>...</b></font>  <font color="#FBE84F"><b>|</b></font>
<font color="#729ECF"><b>86</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>     }
<font color="#729ECF"><b>87</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font> }
   <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|_^</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::too_many_arguments)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments

<font color="#FBE84F"><b>warning</b></font><b>: in an &apos;if&apos; condition, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a &apos;let&apos;</b>
  <font color="#729ECF"><b>--&gt; </b></font>src/main.rs:86:26
   <font color="#729ECF"><b>|</b></font>
<font color="#729ECF"><b>86</b></font> <font color="#729ECF"><b>| </b></font>              .map_err(|e| {
   <font color="#729ECF"><b>| </b></font> <font color="#FBE84F"><b>__________________________^</b></font>
<font color="#729ECF"><b>87</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                 ContextualError::IOError(
<font color="#729ECF"><b>88</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                     &quot;Failed to retrieve symlink&apos;s metadata&quot;.to_string(),
<font color="#729ECF"><b>89</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                     e,
<font color="#729ECF"><b>90</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>                 )
<font color="#729ECF"><b>91</b></font> <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|</b></font>             })?
   <font color="#729ECF"><b>| </b></font><font color="#FBE84F"><b>|_____________^</b></font>
   <font color="#729ECF"><b>|</b></font>
   <font color="#729ECF"><b>= </b></font><b>note</b>: #[warn(clippy::block_in_if_condition_stmt)] on by default
   <font color="#729ECF"><b>= </b></font><b>help</b>: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#block_in_if_condition_stmt

<font color="#89E234"><b>    Finished</b></font> dev [unoptimized + debuginfo] target(s) in 2.81s
</pre>

</details>

## Proposal

* Integrate `clippy` into CI
* Create a `rls.toml` that enables `clippy`

**Comment by svenstaro** [comment]
I like clippy. I'd be ok with enforcing it, but keep in mind that it's not perfect and we might have to ignore some lints.

**Comment by KSXGitHub** [comment]
> we might have to ignore some lints.

We can use `#[allow(...)]` to explicitly ignore them.

**Comment by svenstaro** [comment]
Sure, just something to keep in mind.
