### ISSUE TITLE
Create Distroless Container Image (again)

### ISSUE THREAD

**Issue by genofire** [svenstaro/miniserve#939]
Huhu, out of security perspective.
It would be nice to has an Image without Distro (and all there vulnubilities inside).

This was already, but changed in #904 (to an ubuntu), by coping the binary from builder image to a new `FROM scratch`.

**Comment by lilnasy** [comment]
Google's distroless images are stripped down debians; they are glibc-based, so the miniserve ubuntu image one could easily be made into a distroless one. It's slightly larger than alpine, but still has a smaller attack surface. However, miniserve also depends on libgcc at runtime, which the distroless version has stripped out. It has to be copied in.

Here's a full nonroot distroless Dockerfile for miniserve compiled against glibc.

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM gcr.io/distroless/base-debian11:nonroot
COPY --from=docker.io/debian:stable-20221004-slim /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/
COPY --chmod=nonroot miniserve /app/
# run as non-privileged user
USER nonroot
ENTRYPOINT ["/app/miniserve"]
```

</details>

For reference, I know that [cloudflared](https://github.com/cloudflare/cloudflared/blob/c280d62fe506df2f90fa4343259e08a979124ddd/Dockerfile) also use a distroless image for their glibc-based(?) CLI.

**Comment by lilnasy** [comment]
Happy to help :)
