### ISSUE TITLE
Segmentation Fault in ALMALinux 9.0

### ISSUE THREAD

**Issue by K-JW** [svenstaro/miniserve#953]
Hello developers,

Thank you for providing this useful tool. 

When I run the precompiled binary on `AlmaLinux 9.0 (x86_64)`, I get a segmentation fault.

**Comment by svenstaro** [comment]
That's super weird. Does the OS have some security layer stuff going on such as AppArmor or SELinux? The binaries should be definitely compatible otherwise.

**Comment by K-JW** [comment]
As you might expect, my OS is SELinux-enabled. Can I use `miniserve` without turning off SELinux?

**Comment by svenstaro** [comment]
Sadly I have no idea. Does it work if you compile the binary yourself? Do the container images work in podman?
