### ISSUE TITLE
Crash after restart.

### ISSUE THREAD

**Issue by rtkpX** [svenstaro/miniserve#954]
Program and configuration works just fine, but when I restart my computer, program will start crashing.

Seems that the problem is the TLS certification, when I remove it from the starter the program works, but it worked just fine before restarting and it's crashing now...

**Comment by svenstaro** [comment]
Do you have an error message for me?

**Comment by rtkpX** [comment]
It just crashes leaving no message, app opens then closes.

**Comment by svenstaro** [comment]
What version of miniserve is this and what's your OS?

**Comment by rtkpX** [comment]
0.22.0, Windows 10 Pro

**Comment by rtkpX** [comment]
Now it does give me an error:

`Error: Couldn't access TLS certificate "C:\\Certbot\\live\\www.pabloware.cc\\fullchain.pem"

Caused by:
    Access is denied. (os error 5)`

**Comment by rtkpX** [comment]
Yea, I realized, for some reason it loses permissions every time I restart my pc so I gotta renew the certificate each restart

**Comment by svenstaro** [comment]
I don't think miniserve is at fault here from what you're describing. Could we close this?

**Comment by svenstaro** [comment]
I'll close this for the time being. If you figure out that this is miniserve's fault somehow, I'm happy to look into it.
