### ISSUE TITLE
The directory is sorted first

### ISSUE THREAD

**Issue by fcwys** [svenstaro/miniserve#964]
I hope the directory can be sorted first. It is inconvenient to mix directories and files together.

**Comment by levaitamas** [comment]
Hi @fcwys ! Good news, since [v0.10.4](https://github.com/svenstaro/miniserve/releases/tag/v0.10.4) there is a CLI flag  `-D` or `--dirs-first`, which implements this functionality.

**Comment by fcwys** [comment]
It is expected that this option is enabled by default

**Comment by svenstaro** [comment]
I'm not sure this behavior would necessarily be expected by default. I think the default behavior of other applications is pretty mixed in this regard.
