### ISSUE TITLE
[feather request] Language localisation support ?

### ISSUE THREAD

**Issue by changchichung** [svenstaro/miniserve#982]
I'm trying to translate miniserve to Chinese 
but I can not find localization files in the repository.
is there any documents to show how to do language localisation ??

**Comment by svenstaro** [comment]
Hey, I'm afraid I'm not really interested in maintaining multiple languages in miniserve. That's a big can of worms that I don't want to open. It takes a lot of effort to keep that well-maintained and I just don't have the time.

**Comment by stappersg** [comment]
@changchichung please consider to close this issue that has a polite _"not really interested"_ response.

And now me being rude: _"feather request" should be spelled "feature request"_.
