### ISSUE TITLE
[Feature Request] Simple CGI for bash script

### ISSUE THREAD

**Issue by thenoobtester** [svenstaro/miniserve#995]
Hi there,

awesome mini http/https server, I'm always looking for stuff like this when python -m SimpleHTTPServer is not good enough. One feature which would really be the cherry on the cake is some simple CGI for bash scripts to do some quick processing server-side and return some data.

Thank you for considering this in a future release if it's not too much as I have no idea how much work that would entail.

Kindest regards

**Comment by mailq** [comment]
I'd vote against it.
Because that would make miniserve a fully fledged web-server like nginx or apache.
Instead I would advice to have a look into [shell2http](https://github.com/msoap/shell2http) which is exactly the tool to serve scripts. You can still use both tools in parallel, each doing the thing they are designed for.

**Comment by svenstaro** [comment]
I'm also against this. This would make security in miniserve _so much harder_ and also it would make this not so _mini_ anymore since now it's more like a fully fledged application server. I think at this point you should indeed be looking at other software entirely.

**Comment by svenstaro** [comment]
That said, thank you a lot of the feature suggestion, I certainly do not want to sound too dismissive here and I'm usually pretty lenient about features coming in but sometimes I do have to stay the course of this being a small and obvious server for serving files over HTTP.

**Comment by thenoobtester** [comment]
Thank you for the answers and sorry for the delay, I have been very busy and lost track of this :)
